services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - minio-setup
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    minio:
        image: minio/minio:latest
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: "minioadmin"
            MINIO_ROOT_PASSWORD: "minioadmin"
            MINIO_API_CORS_ALLOW_ORIGIN: "http://localhost,http://127.0.0.1,http://localhost:5173"
        volumes:
            - minio-data:/data
            - ./docker/minio/cors.json:/config/cors.json:ro
        ports:
            - "9000:9000"   # S3 API
            - "9001:9001"   # MinIO console
        networks:
            - sail

    minio-setup:
        image: minio/mc:latest
        depends_on:
            - minio
        entrypoint: >
            sh -lc '
                set -e
                # Wait for MinIO to accept connections (retry for ~2 minutes)
                for i in $$(seq 1 60); do
                mc alias set local http://minio:9000 minioadmin minioadmin && break
                echo "Waiting for MinIO... ($$i/60)"; sleep 2
                done
                # If alias still not set, fail loudly
                mc alias ls | grep -q "^local" || { echo "MinIO not reachable"; exit 1; }

                # Create bucket and lock it down
                mc mb -p local/recordings || true
                mc anonymous set none local/recordings || true

                echo "MinIO bucket ready"
            '
        volumes:
            - ./docker/minio/cors.json:/config/cors.json:ro
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    minio-data:
        driver: local
