<h1 class="font-outfit text-2xl font-bold text-white border-b border-slate-700 pb-3 mb-6 mt-0">ADDITIONAL RULES</h1>
<p class="text-slate-300 leading-relaxed mb-4">The following rules apply to many aspects of the game.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">ROUNDING UP</h2>
<p class="text-slate-300 leading-relaxed mb-4">This game doesn’t use fractions; if you need to round to a whole number, round up unless otherwise specified. When in doubt, resolve any ambiguity in favor of the PCs.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">REROLLING DICE</h2>
<p class="text-slate-300 leading-relaxed mb-4">When a feature allows you to reroll a die, you always take the new result unless the feature specifically says otherwise.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">INCOMING DAMAGE</h2>
<p class="text-slate-300 leading-relaxed mb-4">Incoming damage means the total damage from a single attack or source, before Armor Slots are marked.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">SIMULTANEOUS EFFECTS</h2>
<p class="text-slate-300 leading-relaxed mb-4">If the resolution order of multiple effects is unclear, the person in control of the effects (player or GM) decides what order to resolve them in.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">STACKING EFFECTS</h2>
<p class="text-slate-300 leading-relaxed mb-4">Unless stated otherwise, all effects beside conditions and advantage/disadvantage can stack.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">ONGOING SPELL EFFECTS</h2>
<p class="text-slate-300 leading-relaxed mb-4">If an effect doesn’t have a listed mechanical expiration, it only ends when decided by the controlling player, the GM, or the demands of the fiction.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">SPENDING RESOURCES</h2>
<p class="text-slate-300 leading-relaxed mb-4">Unless an effect states otherwise, you can’t spend Hope or mark Stress multiple times on the same feature to increase or repeat its effects on the same roll.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">USING FEATURES AFTER A ROLL</h2>
<p class="text-slate-300 leading-relaxed mb-4">If a feature allows you to affect a roll after the result has been totaled, you can use it after the GM declares whether the roll succeeds or fails, but not after the consequences unfold or another roll is made.</p>
