<h1 class="font-outfit text-2xl font-bold text-white border-b border-slate-700 pb-3 mb-6 mt-0">ARMOR TABLES</h1>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 1 (LEVEL 1)</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                         | <strong class="text-white font-semibold">BASE THRESHOLDS</strong> | <strong class="text-white font-semibold">BASE SCORE</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                    |
| ------------------------------------------------ | ------------------- | -------------- | ---------------------------------------------- |
| <a href="../armor/Gambeson%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Gambeson Armor</a>     | 5 / 11              | 3              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Flexible:</strong></em> +1 to Evasion                  |
| <a href="../armor/Leather%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Leather Armor</a>       | 6 / 13              | 3              | —                                              |
| <a href="../armor/Chainmail%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Chainmail Armor</a>   | 7 / 15              | 4              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion                     |
| <a href="../armor/Full%20Plate%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Full Plate Armor</a> | 8 / 17              | 4              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Very Heavy:</strong></em> -2 to Evasion; -1 to Agility |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 2 (LEVELS 2–4)</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                       | <strong class="text-white font-semibold">BASE THRESHOLDS</strong> | <strong class="text-white font-semibold">BASE SCORE</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                                             |
| ------------------------------ | ------------------- | -------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../armor/Improved%20Gambeson%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Improved Gambeson Armor</a>    | 7 / 16              | 4              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Flexible:</strong></em> +1 to Evasion                                                                                                                           |
| <a href="../armor/Improved%20Leather%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Improved Leather Armor</a>     | 9 / 20              | 4              | —                                                                                                                                                       |
| <a href="../armor/Improved%20Chainmail%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Improved Chainmail Armor</a>   | 11 / 24             | 5              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion                                                                                                                              |
| <a href="../armor/Improved%20Full%20Plate%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Improved Full Plate Armor</a>  | 13 / 28             | 5              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Very Heavy:</strong></em> -2 to Evasion; -1 to Agility                                                                                                          |
| <a href="../armor/Elundrian%20Chain%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Elundrian Chain Armor</a>      | 9 / 21              | 4              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Warded:</strong></em> You reduce incoming magic damage by your Armor Score before applying it to your damage thresholds.                                        |
| <a href="../armor/Harrowbone%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Harrowbone Armor</a>           | 9 / 21              | 4              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Resilient:</strong></em> Before you mark your last Armor Slot, roll a d6. On a result of 6, reduce the severity by one threshold without marking an Armor Slot. |
| <a href="../armor/Irontree%20Breastplate%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Irontree Breastplate Armor</a> | 9 / 20              | 4              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reinforced:</strong></em> When you mark your last Armor Slot, increase your damage thresholds by +2 until you clear at least 1 Armor Slot.                      |
| <a href="../armor/Runetan%20Floating%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Runetan Floating Armor</a>     | 9 / 20              | 4              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Shifting:</strong></em> When you are targeted for an attack, you can mark an Armor Slot to give the attack roll against you disadvantage.                       |
| <a href="../armor/Tyris%20Soft%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Tyris Soft Armor</a>           | 8 / 18              | 5              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quiet:</strong></em> You gain a +2 bonus to rolls you make to move silently.                                                                                    |
| <a href="../armor/Rosewild%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Rosewild Armor</a>             | 11 / 23             | 5              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Hopeful:</strong></em> When you would spend a Hope, you can mark an Armor Slot instead.                                                                         |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 3 (LEVELS 5–7)</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                                                                 | <strong class="text-white font-semibold">BASE THRESHOLDS</strong> | <strong class="text-white font-semibold">BASE SCORE</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                      |
| ------------------------------------------------------------------------ | ------------------- | -------------- | ---------------------------------------------------------------------------------------------------------------- |
| <a href="../armor/Advanced%20Gambeson%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Gambeson Armor</a>       | 9 / 23              | 5              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Flexible:</strong></em> +1 to Evasion                                                                                    |
| <a href="../armor/Advanced%20Leather%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Leather Armor</a>         | 11 / 27             | 5              | —                                                                                                                |
| <a href="../armor/Advanced%20Chainmail%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Chainmail Armor</a>     | 13 / 31             | 6              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion                                                                                       |
| <a href="../armor/Advanced%20Full%20Plate%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Full Plate Armor</a> | 15 / 35             | 6              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Very Heavy:</strong></em> -2 to Evasion; -1 to Agility                                                                   |
| <a href="../armor/Bellamie%20Fine%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Bellamie Fine Armor</a>               | 11 / 27             | 5              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Gilded:</strong></em> +1 to Presence                                                                                     |
| <a href="../armor/Dragonscale%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Dragonscale Armor</a>                     | 11 / 27             | 5              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Impenetrable:</strong></em> Once per short rest, when you would mark your last Hit Point, you can instead mark a Stress. |
| <a href="../armor/Spiked%20Plate%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Spiked Plate Armor</a>                 | 10 / 25             | 5              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Sharp:</strong></em> On a successful attack against a target within Melee range, add a d4 to the damage roll.            |
| <a href="../armor/Bladefare%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Bladefare Armor</a>                         | 16 / 39             | 6              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Physical:</strong></em> You can’t mark an Armor Slot to reduce magic damage.                                             |
| <a href="../armor/Monetts%20Cloak.md" class="text-amber-400 hover:text-amber-300 underline">Monett’s Cloak</a>                            | 16 / 39             | 6              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Magic:</strong></em> You can’t mark an Armor Slot to reduce physical damage.                                             |
| <a href="../armor/Runes%20of%20Fortification.md" class="text-amber-400 hover:text-amber-300 underline">Runes of Fortification</a>         | 17 / 43             | 6              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Painful:</strong></em> Each time you mark an Armor Slot, you must mark a Stress.                                         |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 4 (LEVELS 8–10)</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                       | <strong class="text-white font-semibold">BASE THRESHOLDS</strong> | <strong class="text-white font-semibold">BASE SCORE</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                  |
| ------------------------------ | ------------------- | -------------- | ---------------------------------------------------------------------------------------------------------------------------- |
| <a href="../armor/Legendary%20Gambeson%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Gambeson Armor</a>   | 11 / 32             | 6              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Flexible:</strong></em> +1 to Evasion                                                                                                |
| <a href="../armor/Legendary%20Leather%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Leather Armor</a>    | 13 / 36             | 6              | —                                                                                                                            |
| <a href="../armor/Legendary%20Chainmail%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Chainmail Armor</a>  | 15 / 40             | 7              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion                                                                                                   |
| <a href="../armor/Legendary%20Full%20Plate%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Full Plate Armor</a> | 17 / 44             | 7              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Very Heavy:</strong></em> -2 to Evasion; -1 to Agility                                                                               |
| <a href="../armor/Dunamis%20Silkchain.md" class="text-amber-400 hover:text-amber-300 underline">Dunamis Silkchain</a>          | 13 / 36             | 7              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Timeslowing:</strong></em> Mark an Armor Slot to roll a d4 and add its result as a bonus to your Evasion against an incoming attack. |
| <a href="../armor/Channeling%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Channeling Armor</a>           | 13 / 36             | 5              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Channeling:</strong></em> +1 to Spellcast Rolls                                                                                      |
| <a href="../armor/Emberwoven%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Emberwoven Armor</a>           | 13 / 36             | 6              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Burning:</strong></em> When an adversary attacks you within Melee range, they mark a Stress.                                         |
| <a href="../armor/Full%20Fortified%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Full Fortified Armor</a>       | 15 / 40             | 4              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Fortified:</strong></em> When you mark an Armor Slot, you reduce the severity of an attack by two thresholds instead of one.         |
| <a href="../armor/Veritas%20Opal%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Veritas Opal Armor</a>         | 13 / 36             | 6              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Truthseeking:</strong></em> This armor glows when another creature within Close range tells a lie.                                   |
| <a href="../armor/Savior%20Chainmail.md" class="text-amber-400 hover:text-amber-300 underline">Savior Chainmail</a>           | 18 / 48             | 8              | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Difficult:</strong></em> -1 to all character traits and Evasion                                                                      |</p>
