<h1 class="font-outfit text-2xl font-bold text-white border-b border-slate-700 pb-3 mb-6 mt-0">COMBAT WHEELCHAIR</h1>
<p class="text-slate-300 leading-relaxed mb-4"><em class="text-amber-300 not-italic">By Mark Thompson</em></p>
<p class="text-slate-300 leading-relaxed mb-4">The combat wheelchair is a ruleset designed to help you play a wheelchair user in Daggerheart. This section provides mechanics and narrative guidance for you to work from, but feel free to adapt the flavor text to best suit your character. Have fun with your character’s wheelchair design, and make it as unique or tailored to them as you please.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">ACTION AND MOVEMENT</h2>
<p class="text-slate-300 leading-relaxed mb-4">When describing how your character moves, you can use descriptions such as the following:</p>
<ul class="text-slate-300 list-disc list-inside mb-4 space-y-1">
<li class="leading-relaxed">“I roll over to the door to see if it’s open.”</li>
<li class="leading-relaxed">“I wheel myself over to the group to ask what’s going on.”</li>
<li class="leading-relaxed">“I pull my brakes and skid to a halt, turning in my seat to level my bow at the intruder.”</li>
</ul>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">CONSEQUENCES</h2>
<p class="text-slate-300 leading-relaxed mb-4">Here are some ways you might describe complications you encounter when your character uses their wheelchair:</p>
<ul class="text-slate-300 list-disc list-inside mb-4 space-y-1">
<li class="leading-relaxed">“I pull my brakes, but I don’t think to account for the loose gravel on the ground.”</li>
<li class="leading-relaxed">“I hit a patch of ice awkwardly and am sent skidding out past my target.”</li>
<li class="leading-relaxed">“I go to push off in pursuit, but one of my front caster wheels snags on a crack in the pavement, stalling me for a moment.”</li>
</ul>
<p class="text-slate-300 leading-relaxed mb-4">GMs should avoid breaking a character’s wheelchair or otherwise removing it from play as a consequence, unless everyone at the table, especially the wheelchair user’s player, gives their approval.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">EVASION</h2>
<p class="text-slate-300 leading-relaxed mb-4">Your character is assumed to be skilled in moving their wheelchair and navigating numerous situations in it. As a result, the only wheelchair that gives a penalty to a PC’s Evasion is the Heavy Frame model.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">BURDEN</h2>
<p class="text-slate-300 leading-relaxed mb-4">All wheelchairs can be maneuvered using one or two hands outside of combat. However, when being used as a weapon, the chair is restricted to requiring one or two hands to perform attacks, depending on the model you’ve chosen. If you’re playing a character who has limited to no mobility in their arms, their wheelchair can be attuned to them by magical means. For example, your character might use a psychic link to guide the chair around like a pseudo-electric wheelchair. All the rules presented here can be tailored and adapted to any character’s needs.</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">CHOOSING YOUR MODEL</h2>
<p class="text-slate-300 leading-relaxed mb-4">All combat wheelchairs are equipped as Primary Weapons. There are three models of wheelchair available: light, heavy, and arcane. You’re encouraged to consider the type of character you’re playing and the class they belong to, then choose the model that best matches that character concept.</p>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">LIGHT FRAME MODELS</h3>
<p class="text-slate-300 leading-relaxed mb-4">Though tough, these wheelchairs have light frames that allow the chair to move with your character in more acrobatic ways. These models are best suited to adventurers who rely on speed and flexibility.</p>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                             | <strong class="text-white font-semibold">TIER</strong> | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong> | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                          |
| ------------------------------------ | -------- | --------- | --------- | ---------- | ---------- | ---------------------------------------------------------------------------------------------------- |
| <strong class="text-white font-semibold">Light-Frame Wheelchair</strong>           | 1        | Agility   | Melee     | d8 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range. |
| <strong class="text-white font-semibold">Improved Light-Frame Wheelchair</strong>  | 2        | Agility   | Melee     | d8+3 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range. |
| <strong class="text-white font-semibold">Advanced Light-Frame Wheelchair</strong>  | 3        | Agility   | Melee     | d8+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range. |
| <strong class="text-white font-semibold">Legendary Light-Frame Wheelchair</strong> | 4        | Agility   | Melee     | d8+9 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range. |</p>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">HEAVY FRAME MODELS</h3>
<p class="text-slate-300 leading-relaxed mb-4">These wheelchairs have bulky and heavier frames, allowing the chair to lend its weight to your character’s attacks. It also makes them a bigger target.</p>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                             | <strong class="text-white font-semibold">TIER</strong> | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong> | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                |
| ------------------------------------ | -------- | --------- | --------- | ---------- | ---------- | -------------------------- |
| <strong class="text-white font-semibold">Heavy-Frame Wheelchair</strong>           | 1        | Strength  | Melee     | d12+3 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion |
| <strong class="text-white font-semibold">Improved Heavy-Frame Wheelchair</strong>  | 2        | Strength  | Melee     | d12+6 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion |
| <strong class="text-white font-semibold">Advanced Heavy-Frame Wheelchair</strong>  | 3        | Strength  | Melee     | d12+9 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion |
| <strong class="text-white font-semibold">Legendary Heavy-Frame Wheelchair</strong> | 4        | Strength  | Melee     | d12+12 phy | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion |</p>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">ARCANE FRAME MODELS</h3>
<p class="text-slate-300 leading-relaxed mb-4">These wheelchairs have frames that are attuned to your character and their magic, allowing them to channel their spells through the chair. Unlike other primary magic weapons, the arcane-frame model doesn’t specify a trait to use when making an attack with it. Instead, you use the Spellcast trait indicated by your subclass.</p>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                              | <strong class="text-white font-semibold">TIER</strong> | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong> | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                        |
| ------------------------------------- | -------- | --------- | --------- | ---------- | ---------- | ---------------------------------- |
| <strong class="text-white font-semibold">Arcane-Frame Wheelchair</strong>           | 1        | Spellcast | Far       | d6 mag     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls |
| <strong class="text-white font-semibold">Improved Arcane-Frame Wheelchair</strong>  | 2        | Spellcast | Far       | d6+3 mag   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls |
| <strong class="text-white font-semibold">Advanced Arcane-Frame Wheelchair</strong>  | 3        | Spellcast | Far       | d6+6 mag   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls |
| <strong class="text-white font-semibold">Legendary Arcane-Frame Wheelchair</strong> | 4        | Spellcast | Far       | d6+9 mag   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls |</p>
