<h1 class="font-outfit text-2xl font-bold text-white border-b border-slate-700 pb-3 mb-6 mt-0">CONSUMABLES</h1>
<p class="text-slate-300 leading-relaxed mb-4">Consumables are loot that can only be used once. You can hold up to five of each consumable at a time. Using a consumable doesn’t require a roll unless required by the GM or the demands of the fiction.</p>
<p class="text-slate-300 leading-relaxed mb-4">To generate a random consumable, choose a rarity, roll the designated dice, and match the total to the item in the table:</p>
<ul class="text-slate-300 list-disc list-inside mb-4 space-y-1">
<li class="leading-relaxed"><strong class="text-white font-semibold">Common:</strong> 1d12 or 2d12</li>
<li class="leading-relaxed"><strong class="text-white font-semibold">Uncommon:</strong> 2d12 or 3d12</li>
<li class="leading-relaxed"><strong class="text-white font-semibold">Rare:</strong> 3d12 or 4d12</li>
<li class="leading-relaxed"><strong class="text-white font-semibold">Legendary:</strong> 4d12 or 5d12</li>
</ul>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">ROLL</strong> | <strong class="text-white font-semibold">LOOT</strong>                                                                         | <strong class="text-white font-semibold">DESCRIPTION</strong>                                                                                                                                                                                                          |
| :------: | -------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
|  <strong class="text-white font-semibold">1</strong>   | <a href="../consumables/Stride%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Stride Potion</a>                               | You gain a +1 bonus to your next Agility Roll.                                                                                                                                                                           |
|  <strong class="text-white font-semibold">2</strong>   | <a href="../consumables/Bolster%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Bolster Potion</a>                             | You gain a +1 bonus to your next Strength Roll.                                                                                                                                                                          |
|  <strong class="text-white font-semibold">3</strong>   | <a href="../consumables/Control%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Control Potion</a>                             | You gain a +1 bonus to your next Finesse Roll.                                                                                                                                                                           |
|  <strong class="text-white font-semibold">4</strong>   | <a href="../consumables/Attune%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Attune Potion</a>                               | You gain a +1 bonus to your next Instinct Roll.                                                                                                                                                                          |
|  <strong class="text-white font-semibold">5</strong>   | <a href="../consumables/Charm%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Charm Potion</a>                                 | You gain a +1 bonus to your next Presence Roll.                                                                                                                                                                          |
|  <strong class="text-white font-semibold">6</strong>   | <a href="../consumables/Enlighten%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Enlighten Potion</a>                         | You gain a +1 bonus to your next Knowledge Roll.                                                                                                                                                                         |
|  <strong class="text-white font-semibold">7</strong>   | <a href="../consumables/Minor%20Health%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Minor Health Potion</a>                 | Clear 1d4 HP.                                                                                                                                                                                                            |
|  <strong class="text-white font-semibold">8</strong>   | <a href="../consumables/Minor%20Stamina%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Minor Stamina Potion</a>               | Clear 1d4 Stress.                                                                                                                                                                                                        |
|  <strong class="text-white font-semibold">9</strong>   | <a href="../consumables/Grindeltooth%20Venom.md" class="text-amber-400 hover:text-amber-300 underline">Grindeltooth Venom</a>                     | You can apply this venom to a weapon that deals physical damage to add a d6 to your next damage roll with that weapon.                                                                                                   |
|  <strong class="text-white font-semibold">10</strong>  | <a href="../consumables/Varik%20Leaves.md" class="text-amber-400 hover:text-amber-300 underline">Varik Leaves</a>                                 | You can eat these paired leaves to immediately gain 2 Hope.                                                                                                                                                              |
|  <strong class="text-white font-semibold">11</strong>  | <a href="../consumables/Vial%20of%20Moondrip.md" class="text-amber-400 hover:text-amber-300 underline">Vial of Moondrip</a>                       | When you drink the contents of this vial, you can see in total darkness until your next rest.                                                                                                                            |
|  <strong class="text-white font-semibold">12</strong>  | <a href="../consumables/Unstable%20Arcane%20Shard.md" class="text-amber-400 hover:text-amber-300 underline">Unstable Arcane Shard</a>             | You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 1d20 magic damage.                                                                          |
|  <strong class="text-white font-semibold">13</strong>  | <a href="../consumables/Potion%20of%20Stability.md" class="text-amber-400 hover:text-amber-300 underline">Potion of Stability</a>                 | You can drink this potion to choose one additional downtime move.                                                                                                                                                        |
|  <strong class="text-white font-semibold">14</strong>  | <a href="../consumables/Improved%20Grindeltooth%20Venom.md" class="text-amber-400 hover:text-amber-300 underline">Improved Grindeltooth Venom</a> | You can apply this venom to a weapon that deals physical damage to add a d8 to your next damage roll with that weapon.                                                                                                   |
|  <strong class="text-white font-semibold">15</strong>  | <a href="../consumables/Morphing%20Clay.md" class="text-amber-400 hover:text-amber-300 underline">Morphing Clay</a>                               | You can spend 4 Hope to use this clay, altering your face enough to make you unrecognizable until your next rest.                                                                                                        |
|  <strong class="text-white font-semibold">16</strong>  | <a href="../consumables/Vial%20of%20Darksmoke.md" class="text-amber-400 hover:text-amber-300 underline">Vial of Darksmoke</a>                     | When an adversary attacks you, use this vial and roll a number of d6 equal to your Agility. Add the highest result to your Evasion against the attack.                                                                   |
|  <strong class="text-white font-semibold">17</strong>  | <a href="../consumables/Jumping%20Root.md" class="text-amber-400 hover:text-amber-300 underline">Jumping Root</a>                                 | Eat this root to leap up to Far range once without needing to roll.                                                                                                                                                      |
|  <strong class="text-white font-semibold">18</strong>  | <a href="../consumables/Snap%20Powder.md" class="text-amber-400 hover:text-amber-300 underline">Snap Powder</a>                                   | Mark a Stress and clear a HP.                                                                                                                                                                                            |
|  <strong class="text-white font-semibold">19</strong>  | <a href="../consumables/Health%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Health Potion</a>                               | Clear 1d4+1 HP.                                                                                                                                                                                                          |
|  <strong class="text-white font-semibold">20</strong>  | <a href="../consumables/Stamina%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Stamina Potion</a>                             | Clear 1d4+1 Stress.                                                                                                                                                                                                      |
|  <strong class="text-white font-semibold">21</strong>  | <a href="../consumables/Armor%20Stitcher.md" class="text-amber-400 hover:text-amber-300 underline">Armor Stitcher</a>                             | You can use this stitcher to spend any number of Hope and clear that many Armor Slots.                                                                                                                                   |
|  <strong class="text-white font-semibold">22</strong>  | <a href="../consumables/Gill%20Salve.md" class="text-amber-400 hover:text-amber-300 underline">Gill Salve</a>                                     | You can apply this salve to your neck to breathe underwater for a number of minutes equal to your level.                                                                                                                 |
|  <strong class="text-white font-semibold">23</strong>  | <a href="../consumables/Replication%20Parchment.md" class="text-amber-400 hover:text-amber-300 underline">Replication Parchment</a>               | By touching this piece of parchment to another, you can perfectly copy the second parchment’s contents. Once used, this parchment becomes mundane paper.                                                                 |
|  <strong class="text-white font-semibold">24</strong>  | <a href="../consumables/Improved%20Arcane%20Shard.md" class="text-amber-400 hover:text-amber-300 underline">Improved Arcane Shard</a>             | You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 2d20 magic damage.                                                                          |
|  <strong class="text-white font-semibold">25</strong>  | <a href="../consumables/Major%20Stride%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Major Stride Potion</a>                 | You gain a +1 bonus to your Agility until your next rest.                                                                                                                                                                |
|  <strong class="text-white font-semibold">26</strong>  | <a href="../consumables/Major%20Bolster%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Major Bolster Potion</a>               | You gain a +1 bonus to your Strength until your next rest.                                                                                                                                                               |
|  <strong class="text-white font-semibold">27</strong>  | <a href="../consumables/Major%20Control%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Major Control Potion</a>               | You gain a +1 bonus to your Finesse until your next rest.                                                                                                                                                                |
|  <strong class="text-white font-semibold">28</strong>  | <a href="../consumables/Major%20Attune%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Major Attune Potion</a>                 | You gain a +1 bonus to your Instinct until your next rest.                                                                                                                                                               |
|  <strong class="text-white font-semibold">29</strong>  | <a href="../consumables/Major%20Charm%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Major Charm Potion</a>                   | You gain a +1 bonus to your Presence until your next rest.                                                                                                                                                               |
|  <strong class="text-white font-semibold">30</strong>  | <a href="../consumables/Major%20Enlighten%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Major Enlighten Potion</a>           | You gain a +1 bonus to your Knowledge until your next rest.                                                                                                                                                              |
|  <strong class="text-white font-semibold">31</strong>  | <a href="../consumables/Blood%20of%20the%20Yorgi.md" class="text-amber-400 hover:text-amber-300 underline">Blood of the Yorgi</a>                 | You can drink this blood to disappear from where you are and immediately reappear at a point you can see within very Far range.                                                                                          |
|  <strong class="text-white font-semibold">32</strong>  | <a href="../consumables/Hornets%20Secret%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Hornet’s Secret Potion</a>            | After drinking this potion, the next successful attack you make critically succeeds.                                                                                                                                     |
|  <strong class="text-white font-semibold">33</strong>  | <a href="../consumables/Redthorn%20Saliva.md" class="text-amber-400 hover:text-amber-300 underline">Redthorn Saliva</a>                           | You can apply this saliva to a weapon that deals physical damage to add a d12 to your next damage roll with that weapon.                                                                                                 |
|  <strong class="text-white font-semibold">34</strong>  | <a href="../consumables/Channelstone.md" class="text-amber-400 hover:text-amber-300 underline">Channelstone</a>                                   | You can use this stone to take a spell or grimoire from your vault, use it once, and return it to your vault.                                                                                                            |
|  <strong class="text-white font-semibold">35</strong>  | <a href="../consumables/Mythic%20Dust.md" class="text-amber-400 hover:text-amber-300 underline">Mythic Dust</a>                                   | You can apply this dust to a weapon that deals magic damage to add a d12 to your next damage roll with that weapon.                                                                                                      |
|  <strong class="text-white font-semibold">36</strong>  | <a href="../consumables/Acidpaste.md" class="text-amber-400 hover:text-amber-300 underline">Acidpaste</a>                                         | This paste eats away walls and other surfaces in bright flashes.                                                                                                                                                         |
|  <strong class="text-white font-semibold">37</strong>  | <a href="../consumables/Hopehold%20Flare.md" class="text-amber-400 hover:text-amber-300 underline">Hopehold Flare</a>                             | When you use this flare, allies within Close range roll a d6 when they spend a Hope. On a result of 6, they gain the effect of that Hope without spending it. The flare lasts until the end of the scene.                |
|  <strong class="text-white font-semibold">38</strong>  | <a href="../consumables/Major%20Arcane%20Shard.md" class="text-amber-400 hover:text-amber-300 underline">Major Arcane Shard</a>                   | You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 4d20 magic damage.                                                                          |
|  <strong class="text-white font-semibold">39</strong>  | <a href="../consumables/Featherbone.md" class="text-amber-400 hover:text-amber-300 underline">Featherbone</a>                                     | You can use this bone to control your falling speed for a number of minutes equal to your level.                                                                                                                         |
|  <strong class="text-white font-semibold">40</strong>  | <a href="../consumables/Circle%20of%20the%20Void.md" class="text-amber-400 hover:text-amber-300 underline">Circle of the Void</a>                 | Mark a Stress to create a void that extends up to Far range. No magic can be cast inside the void, and creatures within the void are immune to magic damage.                                                             |
|  <strong class="text-white font-semibold">41</strong>  | <a href="../consumables/Sun%20Tree%20Sap.md" class="text-amber-400 hover:text-amber-300 underline">Sun Tree Sap</a>                               | Consume this sap to roll a d6. On a result of 5–6, clear 2 HP. On a result of 2–4, clear 3 Stress. On a result of 1, see through the veil of death and return unscathed, gaining one scar.                               |
|  <strong class="text-white font-semibold">42</strong>  | <a href="../consumables/Dripfang%20Poison.md" class="text-amber-400 hover:text-amber-300 underline">Dripfang Poison</a>                           | A creature who consumes this poison takes 2d10 direct magic damage.                                                                                                                                                      |
|  <strong class="text-white font-semibold">43</strong>  | <a href="../consumables/Major%20Health%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Major Health Potion</a>                 | Clear 1d4+2 HP.                                                                                                                                                                                                          |
|  <strong class="text-white font-semibold">44</strong>  | <a href="../consumables/Major%20Stamina%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Major Stamina Potion</a>               | Clear 1d4+2 Stress.                                                                                                                                                                                                      |
|  <strong class="text-white font-semibold">45</strong>  | <a href="../consumables/Ogre%20Musk.md" class="text-amber-400 hover:text-amber-300 underline">Ogre Musk</a>                                       | You can use this musk to prevent anyone from tracking you by mundane or magical means until your next rest.                                                                                                              |
|  <strong class="text-white font-semibold">46</strong>  | <a href="../consumables/Wingsprout.md" class="text-amber-400 hover:text-amber-300 underline">Wingsprout</a>                                       | You gain magic wings that allow you to fly for a number of minutes equal to your level.                                                                                                                                  |
|  <strong class="text-white font-semibold">47</strong>  | <a href="../consumables/Jar%20of%20Lost%20Voices.md" class="text-amber-400 hover:text-amber-300 underline">Jar of Lost Voices</a>                 | You can open this jar to release a deafening echo of voices for a number of minutes equal to your Instinct. Creatures within Far range unprepared for the sound take 6d8 magic damage.                                   |
|  <strong class="text-white font-semibold">48</strong>  | <a href="../consumables/Dragonbloom%20Tea.md" class="text-amber-400 hover:text-amber-300 underline">Dragonbloom Tea</a>                           | You can drink this tea to unleash a fiery breath attack. Make an Instinct Roll against all adversaries in front of you within Close range. Targets you succeed against take 2d20 physical damage using your Proficiency. |
|  <strong class="text-white font-semibold">49</strong>  | <a href="../consumables/Bridge%20Seed.md" class="text-amber-400 hover:text-amber-300 underline">Bridge Seed</a>                                   | Thick vines grow from your location to a point of your choice within Far range, allowing you to climb up or across them. The vines dissipate on your next short rest.                                                    |
|  <strong class="text-white font-semibold">50</strong>  | <a href="../consumables/Sleeping%20Sap.md" class="text-amber-400 hover:text-amber-300 underline">Sleeping Sap</a>                                 | You can drink this potion to fall asleep for a full night’s rest. You clear all Stress upon waking.                                                                                                                      |
|  <strong class="text-white font-semibold">51</strong>  | <a href="../consumables/Feast%20of%20Xurla.md" class="text-amber-400 hover:text-amber-300 underline">Feast of Xurla</a>                           | You can eat this meal to clear all HP and Stress and gain 1d4 Hope.                                                                                                                                                      |
|  <strong class="text-white font-semibold">52</strong>  | <a href="../consumables/Bonding%20Honey.md" class="text-amber-400 hover:text-amber-300 underline">Bonding Honey</a>                               | This honey can be used to glue two objects together permanently.                                                                                                                                                         |
|  <strong class="text-white font-semibold">53</strong>  | <a href="../consumables/Shrinking%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Shrinking Potion</a>                         | You can drink this potion to halve your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Agility and a –1 penalty to your Proficiency.                              |
|  <strong class="text-white font-semibold">54</strong>  | <a href="../consumables/Growing%20Potion.md" class="text-amber-400 hover:text-amber-300 underline">Growing Potion</a>                             | You can drink this potion to double your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Strength and a +1 bonus to your Proficiency.                              |
|  <strong class="text-white font-semibold">55</strong>  | <a href="../consumables/Knowledge%20Stone.md" class="text-amber-400 hover:text-amber-300 underline">Knowledge Stone</a>                           | If you die while holding this stone, an ally can take a card from your loadout to place in their loadout or vault. After they take this knowledge, the stone crumbles.                                                   |
|  <strong class="text-white font-semibold">56</strong>  | <a href="../consumables/Sweet%20Moss.md" class="text-amber-400 hover:text-amber-300 underline">Sweet Moss</a>                                     | You can consume this moss during a rest to clear 1d4 HP or 1d4 Stress.                                                                                                                                                   |
|  <strong class="text-white font-semibold">57</strong>  | <a href="../consumables/Blinding%20Orb.md" class="text-amber-400 hover:text-amber-300 underline">Blinding Orb</a>                                 | You can activate this orb to create a flash of bright light. All targets within Close range become Blinded until they mark HP.                                                                                           |
|  <strong class="text-white font-semibold">58</strong>  | <a href="../consumables/Death%20Tea.md" class="text-amber-400 hover:text-amber-300 underline">Death Tea</a>                                       | After you drink this tea, you instantly kill your target when you critically succeed on an attack. If you don’t critically succeed on an attack before your next long rest, you die.                                     |
|  <strong class="text-white font-semibold">59</strong>  | <a href="../consumables/Mirror%20of%20Marigold.md" class="text-amber-400 hover:text-amber-300 underline">Mirror of Marigold</a>                   | When you take damage, you can spend a Hope to negate that damage, after which the mirror shatters.                                                                                                                       |
|  <strong class="text-white font-semibold">60</strong>  | <a href="../consumables/Stardrop.md" class="text-amber-400 hover:text-amber-300 underline">Stardrop</a>                                           | You can use this stardrop to summon a hailstorm of comets that deals 8d20 physical damage to all targets within Very Far range.                                                                                          |</p>
