<h1 class="font-outfit text-2xl font-bold text-white border-b border-slate-700 pb-3 mb-6 mt-0">DOMAIN CARD REFERENCE</h1>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">ARCANA DOMAIN</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">Level</strong> | <strong class="text-white font-semibold">Option 1</strong>                                             | <strong class="text-white font-semibold">Option 2</strong>                                               | <strong class="text-white font-semibold">Option 3</strong>                             |
| :-------: | -------------------------------------------------------- | ---------------------------------------------------------- | ---------------------------------------- |
|   <strong class="text-white font-semibold">1</strong>   | <a href="../abilities/Rune%20Ward.md" class="text-amber-400 hover:text-amber-300 underline">Rune Ward</a>                 | <a href="../abilities/Unleash%20Chaos.md" class="text-amber-400 hover:text-amber-300 underline">Unleash Chaos</a>           | <a href="../abilities/Wall%20Walk.md" class="text-amber-400 hover:text-amber-300 underline">Wall Walk</a> |
|   <strong class="text-white font-semibold">2</strong>   | <a href="../abilities/Cinder%20Grasp.md" class="text-amber-400 hover:text-amber-300 underline">Cinder Grasp</a>           | <a href="../abilities/Floating%20Eye.md" class="text-amber-400 hover:text-amber-300 underline">Floating Eye</a>             | —                                        |
|   <strong class="text-white font-semibold">3</strong>   | <a href="../abilities/Counterspell.md" class="text-amber-400 hover:text-amber-300 underline">Counterspell</a>             | <a href="../abilities/Flight.md" class="text-amber-400 hover:text-amber-300 underline">Flight</a>                           | —                                        |
|   <strong class="text-white font-semibold">4</strong>   | <a href="../abilities/Blink%20Out.md" class="text-amber-400 hover:text-amber-300 underline">Blink Out</a>                 | <a href="../abilities/Preservation%20Blast.md" class="text-amber-400 hover:text-amber-300 underline">Preservation Blast</a> | —                                        |
|   <strong class="text-white font-semibold">5</strong>   | <a href="../abilities/Chain%20Lightning.md" class="text-amber-400 hover:text-amber-300 underline">Chain Lightning</a>     | <a href="../abilities/Premonition.md" class="text-amber-400 hover:text-amber-300 underline">Premonition</a>                 | —                                        |
|   <strong class="text-white font-semibold">6</strong>   | <a href="../abilities/Rift%20Walker.md" class="text-amber-400 hover:text-amber-300 underline">Rift Walker</a>             | <a href="../abilities/Telekinesis.md" class="text-amber-400 hover:text-amber-300 underline">Telekinesis</a>                 | —                                        |
|   <strong class="text-white font-semibold">7</strong>   | <a href="../abilities/Arcana-Touched.md" class="text-amber-400 hover:text-amber-300 underline">Arcana-Touched</a>         | <a href="../abilities/Cloaking%20Blast.md" class="text-amber-400 hover:text-amber-300 underline">Cloaking Blast</a>         | —                                        |
|   <strong class="text-white font-semibold">8</strong>   | <a href="../abilities/Arcane%20Reflection.md" class="text-amber-400 hover:text-amber-300 underline">Arcane Reflection</a> | <a href="../abilities/Confusing%20Aura.md" class="text-amber-400 hover:text-amber-300 underline">Confusing Aura</a>         | —                                        |
|   <strong class="text-white font-semibold">9</strong>   | <a href="../abilities/Earthquake.md" class="text-amber-400 hover:text-amber-300 underline">Earthquake</a>                 | <a href="../abilities/Sensory%20Projection.md" class="text-amber-400 hover:text-amber-300 underline">Sensory Projection</a> | —                                        |
|  <strong class="text-white font-semibold">10</strong>   | <a href="../abilities/Adjust%20Reality.md" class="text-amber-400 hover:text-amber-300 underline">Adjust Reality</a>       | <a href="../abilities/Falling%20Sky.md" class="text-amber-400 hover:text-amber-300 underline">Falling Sky</a>               | —                                        |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">BLADE DOMAIN</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">Level</strong> | <strong class="text-white font-semibold">Option 1</strong>                                           | <strong class="text-white font-semibold">Option 2</strong>                                             | <strong class="text-white font-semibold">Option 3</strong>                           |
| :-------: | ------------------------------------------------------ | -------------------------------------------------------- | -------------------------------------- |
|   <strong class="text-white font-semibold">1</strong>   | <a href="../abilities/Get%20Back%20Up.md" class="text-amber-400 hover:text-amber-300 underline">Get Back Up</a>         | <a href="../abilities/Not%20Good%20Enough.md" class="text-amber-400 hover:text-amber-300 underline">Not Good Enough</a>   | <a href="../abilities/Whirlwind.md" class="text-amber-400 hover:text-amber-300 underline">Whirlwind</a> |
|   <strong class="text-white font-semibold">2</strong>   | <a href="../abilities/A%20Soldiers%20Bond.md" class="text-amber-400 hover:text-amber-300 underline">A Soldiers Bond</a> | <a href="../abilities/Reckless.md" class="text-amber-400 hover:text-amber-300 underline">Reckless</a>                     | —                                      |
|   <strong class="text-white font-semibold">3</strong>   | <a href="../abilities/Scramble.md" class="text-amber-400 hover:text-amber-300 underline">Scramble</a>                   | <a href="../abilities/Versatile%20Fighter.md" class="text-amber-400 hover:text-amber-300 underline">Versatile Fighter</a> | —                                      |
|   <strong class="text-white font-semibold">4</strong>   | <a href="../abilities/Deadly%20Focus.md" class="text-amber-400 hover:text-amber-300 underline">Deadly Focus</a>         | <a href="../abilities/Fortified%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Fortified Armor</a>     | —                                      |
|   <strong class="text-white font-semibold">5</strong>   | <a href="../abilities/Champions%20Edge.md" class="text-amber-400 hover:text-amber-300 underline">Champions Edge</a>     | <a href="../abilities/Vitality.md" class="text-amber-400 hover:text-amber-300 underline">Vitality</a>                     | —                                      |
|   <strong class="text-white font-semibold">6</strong>   | <a href="../abilities/Battle-Hardened.md" class="text-amber-400 hover:text-amber-300 underline">Battle-Hardened</a>     | <a href="../abilities/Rage%20Up.md" class="text-amber-400 hover:text-amber-300 underline">Rage Up</a>                     | —                                      |
|   <strong class="text-white font-semibold">7</strong>   | <a href="../abilities/Blade-Touched.md" class="text-amber-400 hover:text-amber-300 underline">Blade-Touched</a>         | <a href="../abilities/Glancing%20Blow.md" class="text-amber-400 hover:text-amber-300 underline">Glancing Blow</a>         | —                                      |
|   <strong class="text-white font-semibold">8</strong>   | <a href="../abilities/Battle%20Cry.md" class="text-amber-400 hover:text-amber-300 underline">Battle Cry</a>             | <a href="../abilities/Frenzy.md" class="text-amber-400 hover:text-amber-300 underline">Frenzy</a>                         | —                                      |
|   <strong class="text-white font-semibold">9</strong>   | <a href="../abilities/Gore%20and%20Glory.md" class="text-amber-400 hover:text-amber-300 underline">Gore and Glory</a>   | <a href="../abilities/Reapers%20Strike.md" class="text-amber-400 hover:text-amber-300 underline">Reapers Strike</a>       | —                                      |
|  <strong class="text-white font-semibold">10</strong>   | <a href="../abilities/Battle%20Monster.md" class="text-amber-400 hover:text-amber-300 underline">Battle Monster</a>     | <a href="../abilities/Onslaught.md" class="text-amber-400 hover:text-amber-300 underline">Onslaught</a>                   | —                                      |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">BONE DOMAIN</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">Level</strong> | <strong class="text-white font-semibold">Option 1</strong>                                         | <strong class="text-white font-semibold">Option 2</strong>                                               | <strong class="text-white font-semibold">Option 3</strong>                               |
| :-------: | ---------------------------------------------------- | ---------------------------------------------------------- | ------------------------------------------ |
|   <strong class="text-white font-semibold">1</strong>   | <a href="../abilities/Deft%20Maneuvers.md" class="text-amber-400 hover:text-amber-300 underline">Deft Maneuvers</a>   | <a href="../abilities/I%20See%20It%20Coming.md" class="text-amber-400 hover:text-amber-300 underline">I See It Coming</a>   | <a href="../abilities/Untouchable.md" class="text-amber-400 hover:text-amber-300 underline">Untouchable</a> |
|   <strong class="text-white font-semibold">2</strong>   | <a href="../abilities/Ferocity.md" class="text-amber-400 hover:text-amber-300 underline">Ferocity</a>                 | <a href="../abilities/Strategic%20Approach.md" class="text-amber-400 hover:text-amber-300 underline">Strategic Approach</a> | —                                          |
|   <strong class="text-white font-semibold">3</strong>   | <a href="../abilities/Brace.md" class="text-amber-400 hover:text-amber-300 underline">Brace</a>                       | <a href="../abilities/Tactician.md" class="text-amber-400 hover:text-amber-300 underline">Tactician</a>                     | —                                          |
|   <strong class="text-white font-semibold">4</strong>   | <a href="../abilities/Boost.md" class="text-amber-400 hover:text-amber-300 underline">Boost</a>                       | <a href="../abilities/Redirect.md" class="text-amber-400 hover:text-amber-300 underline">Redirect</a>                       | —                                          |
|   <strong class="text-white font-semibold">5</strong>   | <a href="../abilities/Know%20Thy%20Enemy.md" class="text-amber-400 hover:text-amber-300 underline">Know Thy Enemy</a> | <a href="../abilities/Signature%20Move.md" class="text-amber-400 hover:text-amber-300 underline">Signature Move</a>         | —                                          |
|   <strong class="text-white font-semibold">6</strong>   | <a href="../abilities/Rapid%20Riposte.md" class="text-amber-400 hover:text-amber-300 underline">Rapid Riposte</a>     | <a href="../abilities/Recovery.md" class="text-amber-400 hover:text-amber-300 underline">Recovery</a>                       | —                                          |
|   <strong class="text-white font-semibold">7</strong>   | <a href="../abilities/Bone-Touched.md" class="text-amber-400 hover:text-amber-300 underline">Bone-Touched</a>         | <a href="../abilities/Cruel%20Precision.md" class="text-amber-400 hover:text-amber-300 underline">Cruel Precision</a>       | —                                          |
|   <strong class="text-white font-semibold">8</strong>   | <a href="../abilities/Breaking%20Blow.md" class="text-amber-400 hover:text-amber-300 underline">Breaking Blow</a>     | <a href="../abilities/Wrangle.md" class="text-amber-400 hover:text-amber-300 underline">Wrangle</a>                         | —                                          |
|   <strong class="text-white font-semibold">9</strong>   | <a href="../abilities/On%20the%20Brink.md" class="text-amber-400 hover:text-amber-300 underline">On The Brink</a>     | <a href="../abilities/Splintering%20Strike.md" class="text-amber-400 hover:text-amber-300 underline">Splintering Strike</a> | —                                          |
|  <strong class="text-white font-semibold">10</strong>   | <a href="../abilities/Deathrun.md" class="text-amber-400 hover:text-amber-300 underline">Deathrun</a>                 | <a href="../abilities/Swift%20Step.md" class="text-amber-400 hover:text-amber-300 underline">Swift Step</a>                 | —                                          |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">CODEX DOMAIN</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">Level</strong> | <strong class="text-white font-semibold">Option 1</strong>                                         | <strong class="text-white font-semibold">Option 2</strong>                                                     | <strong class="text-white font-semibold">Option 3</strong>                                       |
| :-------: | ---------------------------------------------------- | ---------------------------------------------------------------- | -------------------------------------------------- |
|   <strong class="text-white font-semibold">1</strong>   | <a href="../abilities/Book%20of%20Ava.md" class="text-amber-400 hover:text-amber-300 underline">Book of Ava</a>       | <a href="../abilities/Book%20of%20Illiat.md" class="text-amber-400 hover:text-amber-300 underline">Book of Illiat</a>             | <a href="../abilities/Book%20of%20Tyfar.md" class="text-amber-400 hover:text-amber-300 underline">Book of Tyfar</a> |
|   <strong class="text-white font-semibold">2</strong>   | <a href="../abilities/Book%20of%20Sitil.md" class="text-amber-400 hover:text-amber-300 underline">Book of Sitil</a>   | <a href="../abilities/Book%20of%20Vagras.md" class="text-amber-400 hover:text-amber-300 underline">Book of Vagras</a>             | —                                                  |
|   <strong class="text-white font-semibold">3</strong>   | <a href="../abilities/Book%20of%20Korvax.md" class="text-amber-400 hover:text-amber-300 underline">Book of Korvax</a> | <a href="../abilities/Book%20of%20Norai.md" class="text-amber-400 hover:text-amber-300 underline">Book of Norai</a>               | —                                                  |
|   <strong class="text-white font-semibold">4</strong>   | <a href="../abilities/Book%20of%20Exota.md" class="text-amber-400 hover:text-amber-300 underline">Book of Exota</a>   | <a href="../abilities/Book%20of%20Grynn.md" class="text-amber-400 hover:text-amber-300 underline">Book of Grynn</a>               | —                                                  |
|   <strong class="text-white font-semibold">5</strong>   | <a href="../abilities/Manifest%20Wall.md" class="text-amber-400 hover:text-amber-300 underline">Manifest Wall</a>     | <a href="../abilities/Teleport.md" class="text-amber-400 hover:text-amber-300 underline">Teleport</a>                             | —                                                  |
|   <strong class="text-white font-semibold">6</strong>   | <a href="../abilities/Banish.md" class="text-amber-400 hover:text-amber-300 underline">Banish</a>                     | <a href="../abilities/Sigil%20of%20Retribution.md" class="text-amber-400 hover:text-amber-300 underline">Sigil of Retribution</a> | —                                                  |
|   <strong class="text-white font-semibold">7</strong>   | <a href="../abilities/Book%20of%20Homet.md" class="text-amber-400 hover:text-amber-300 underline">Book of Homet</a>   | <a href="../abilities/Codex-Touched.md" class="text-amber-400 hover:text-amber-300 underline">Codex-Touched</a>                   | —                                                  |
|   <strong class="text-white font-semibold">8</strong>   | <a href="../abilities/Book%20of%20Vyola.md" class="text-amber-400 hover:text-amber-300 underline">Book of Vyola</a>   | <a href="../abilities/Safe%20Haven.md" class="text-amber-400 hover:text-amber-300 underline">Safe Haven</a>                       | —                                                  |
|   <strong class="text-white font-semibold">9</strong>   | <a href="../abilities/Book%20of%20Ronin.md" class="text-amber-400 hover:text-amber-300 underline">Book of Ronin</a>   | <a href="../abilities/Disintegration%20Wave.md" class="text-amber-400 hover:text-amber-300 underline">Disintegration Wave</a>     | —                                                  |
|  <strong class="text-white font-semibold">10</strong>   | <a href="../abilities/Book%20of%20Yarrow.md" class="text-amber-400 hover:text-amber-300 underline">Book of Yarrow</a> | <a href="../abilities/Transcendent%20Union.md" class="text-amber-400 hover:text-amber-300 underline">Transcendent Union</a>       | —                                                  |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">GRACE DOMAIN</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">Level</strong> | <strong class="text-white font-semibold">Option 1</strong>                                             | <strong class="text-white font-semibold">Option 2</strong>                                                     | <strong class="text-white font-semibold">Option 3</strong>                                                 |
| :-------: | -------------------------------------------------------- | ---------------------------------------------------------------- | ------------------------------------------------------------ |
|   <strong class="text-white font-semibold">1</strong>   | <a href="../abilities/Deft%20Deceiver.md" class="text-amber-400 hover:text-amber-300 underline">Deft Deceiver</a>         | <a href="../abilities/Enrapture.md" class="text-amber-400 hover:text-amber-300 underline">Enrapture</a>                           | <a href="../abilities/Inspirational%20Words.md" class="text-amber-400 hover:text-amber-300 underline">Inspirational Words</a> |
|   <strong class="text-white font-semibold">2</strong>   | <a href="../abilities/Tell%20No%20Lies.md" class="text-amber-400 hover:text-amber-300 underline">Tell No Lies</a>         | <a href="../abilities/Troublemaker.md" class="text-amber-400 hover:text-amber-300 underline">Troublemaker</a>                     | —                                                            |
|   <strong class="text-white font-semibold">3</strong>   | <a href="../abilities/Hypnotic%20Shimmer.md" class="text-amber-400 hover:text-amber-300 underline">Hypnotic Shimmer</a>   | <a href="../abilities/Invisibility.md" class="text-amber-400 hover:text-amber-300 underline">Invisibility</a>                     | —                                                            |
|   <strong class="text-white font-semibold">4</strong>   | <a href="../abilities/Soothing%20Speech.md" class="text-amber-400 hover:text-amber-300 underline">Soothing Speech</a>     | <a href="../abilities/Through%20Your%20Eyes.md" class="text-amber-400 hover:text-amber-300 underline">Through Your Eyes</a>       | —                                                            |
|   <strong class="text-white font-semibold">5</strong>   | <a href="../abilities/Thought%20Delver.md" class="text-amber-400 hover:text-amber-300 underline">Thought Delver</a>       | <a href="../abilities/Words%20of%20Discord.md" class="text-amber-400 hover:text-amber-300 underline">Words of Discord</a>         | —                                                            |
|   <strong class="text-white font-semibold">6</strong>   | <a href="../abilities/Never%20Upstaged.md" class="text-amber-400 hover:text-amber-300 underline">Never Upstaged</a>       | <a href="../abilities/Share%20the%20Burden.md" class="text-amber-400 hover:text-amber-300 underline">Share The Burden</a>         | —                                                            |
|   <strong class="text-white font-semibold">7</strong>   | <a href="../abilities/Endless%20Charisma.md" class="text-amber-400 hover:text-amber-300 underline">Endless Charisma</a>   | <a href="../abilities/Grace-Touched.md" class="text-amber-400 hover:text-amber-300 underline">Grace-Touched</a>                   | —                                                            |
|   <strong class="text-white font-semibold">8</strong>   | <a href="../abilities/Astral%20Projection.md" class="text-amber-400 hover:text-amber-300 underline">Astral Projection</a> | <a href="../abilities/Mass%20Enrapture.md" class="text-amber-400 hover:text-amber-300 underline">Mass Enrapture</a>               | —                                                            |
|   <strong class="text-white font-semibold">9</strong>   | <a href="../abilities/Copycat.md" class="text-amber-400 hover:text-amber-300 underline">Copycat</a>                       | <a href="../abilities/Master%20of%20the%20Craft.md" class="text-amber-400 hover:text-amber-300 underline">Master of The Craft</a> | —                                                            |
|  <strong class="text-white font-semibold">10</strong>   | <a href="../abilities/Encore.md" class="text-amber-400 hover:text-amber-300 underline">Encore</a>                         | <a href="../abilities/Notorious.md" class="text-amber-400 hover:text-amber-300 underline">Notorious</a>                           | —                                                            |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">MIDNIGHT DOMAIN</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">Level</strong> | <strong class="text-white font-semibold">Option 1</strong>                                             | <strong class="text-white font-semibold">Option 2</strong>                                                     | <strong class="text-white font-semibold">Option 3</strong>                                           |
| :-------: | -------------------------------------------------------- | ---------------------------------------------------------------- | ------------------------------------------------------ |
|   <strong class="text-white font-semibold">1</strong>   | <a href="../abilities/Pick%20and%20Pull.md" class="text-amber-400 hover:text-amber-300 underline">Pick and Pull</a>       | <a href="../abilities/Rain%20of%20Blades.md" class="text-amber-400 hover:text-amber-300 underline">Rain of Blades</a>             | <a href="../abilities/Uncanny%20Disguise.md" class="text-amber-400 hover:text-amber-300 underline">Uncanny Disguise</a> |
|   <strong class="text-white font-semibold">2</strong>   | <a href="../abilities/Midnight%20Spirit.md" class="text-amber-400 hover:text-amber-300 underline">Midnight Spirit</a>     | <a href="../abilities/Shadowbind.md" class="text-amber-400 hover:text-amber-300 underline">Shadowbind</a>                         | —                                                      |
|   <strong class="text-white font-semibold">3</strong>   | <a href="../abilities/Chokehold.md" class="text-amber-400 hover:text-amber-300 underline">Chokehold</a>                   | <a href="../abilities/Veil%20of%20Night.md" class="text-amber-400 hover:text-amber-300 underline">Veil of Night</a>               | —                                                      |
|   <strong class="text-white font-semibold">4</strong>   | <a href="../abilities/Stealth%20Expertise.md" class="text-amber-400 hover:text-amber-300 underline">Stealth Expertise</a> | <a href="../abilities/Glyph%20of%20Nightfall.md" class="text-amber-400 hover:text-amber-300 underline">Glyph of Nightfall</a>     | —                                                      |
|   <strong class="text-white font-semibold">5</strong>   | <a href="../abilities/Hush.md" class="text-amber-400 hover:text-amber-300 underline">Hush</a>                             | <a href="../abilities/Phantom%20Retreat.md" class="text-amber-400 hover:text-amber-300 underline">Phantom Retreat</a>             | —                                                      |
|   <strong class="text-white font-semibold">6</strong>   | <a href="../abilities/Dark%20Whispers.md" class="text-amber-400 hover:text-amber-300 underline">Dark Whispers</a>         | <a href="../abilities/Mass%20Disguise.md" class="text-amber-400 hover:text-amber-300 underline">Mass Disguise</a>                 | —                                                      |
|   <strong class="text-white font-semibold">7</strong>   | <a href="../abilities/Midnight-Touched.md" class="text-amber-400 hover:text-amber-300 underline">Midnight-Touched</a>     | <a href="../abilities/Vanishing%20Dodge.md" class="text-amber-400 hover:text-amber-300 underline">Vanishing Dodge</a>             | —                                                      |
|   <strong class="text-white font-semibold">8</strong>   | <a href="../abilities/Shadowhunter.md" class="text-amber-400 hover:text-amber-300 underline">Shadowhunter</a>             | <a href="../abilities/Spellcharge.md" class="text-amber-400 hover:text-amber-300 underline">Spellcharge</a>                       | —                                                      |
|   <strong class="text-white font-semibold">9</strong>   | <a href="../abilities/Night%20Terror.md" class="text-amber-400 hover:text-amber-300 underline">Night Terror</a>           | <a href="../abilities/Twilight%20Toll.md" class="text-amber-400 hover:text-amber-300 underline">Twilight Toll</a>                 | —                                                      |
|  <strong class="text-white font-semibold">10</strong>   | <a href="../abilities/Eclipse.md" class="text-amber-400 hover:text-amber-300 underline">Eclipse</a>                       | <a href="../abilities/Specter%20of%20the%20Dark.md" class="text-amber-400 hover:text-amber-300 underline">Specter of The Dark</a> | —                                                      |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">SAGE DOMAIN</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">Level</strong> | <strong class="text-white font-semibold">Option 1</strong>                                                   | <strong class="text-white font-semibold">Option 2</strong>                                                   | <strong class="text-white font-semibold">Option 3</strong>                                           |
| :-------: | -------------------------------------------------------------- | -------------------------------------------------------------- | ------------------------------------------------------ |
|   <strong class="text-white font-semibold">1</strong>   | <a href="../abilities/Gifted%20Tracker.md" class="text-amber-400 hover:text-amber-300 underline">Gifted Tracker</a>             | <a href="../abilities/Natures%20Tongue.md" class="text-amber-400 hover:text-amber-300 underline">Nature's Tongue</a>            | <a href="../abilities/Vicious%20Entangle.md" class="text-amber-400 hover:text-amber-300 underline">Vicious Entangle</a> |
|   <strong class="text-white font-semibold">2</strong>   | <a href="../abilities/Conjure%20Swarm.md" class="text-amber-400 hover:text-amber-300 underline">Conjure Swarm</a>               | <a href="../abilities/Natural%20Familiar.md" class="text-amber-400 hover:text-amber-300 underline">Natural Familiar</a>         | —                                                      |
|   <strong class="text-white font-semibold">3</strong>   | <a href="../abilities/Corrosive%20Projectile.md" class="text-amber-400 hover:text-amber-300 underline">Corrosive Projectile</a> | <a href="../abilities/Towering%20Stalk.md" class="text-amber-400 hover:text-amber-300 underline">Towering Stalk</a>             | —                                                      |
|   <strong class="text-white font-semibold">4</strong>   | <a href="../abilities/Death%20Grip.md" class="text-amber-400 hover:text-amber-300 underline">Death Grip</a>                     | <a href="../abilities/Healing%20Field.md" class="text-amber-400 hover:text-amber-300 underline">Healing Field</a>               | —                                                      |
|   <strong class="text-white font-semibold">5</strong>   | <a href="../abilities/Thorn%20Skin.md" class="text-amber-400 hover:text-amber-300 underline">Thorn Skin</a>                     | <a href="../abilities/Wild%20Fortress.md" class="text-amber-400 hover:text-amber-300 underline">Wild Fortress</a>               | —                                                      |
|   <strong class="text-white font-semibold">6</strong>   | <a href="../abilities/Conjured%20Steeds.md" class="text-amber-400 hover:text-amber-300 underline">Conjured Steeds</a>           | <a href="../abilities/Forager.md" class="text-amber-400 hover:text-amber-300 underline">Forager</a>                             | —                                                      |
|   <strong class="text-white font-semibold">7</strong>   | <a href="../abilities/Sage-Touched.md" class="text-amber-400 hover:text-amber-300 underline">Sage-Touched</a>                   | <a href="../abilities/Wild%20Surge.md" class="text-amber-400 hover:text-amber-300 underline">Wild Surge</a>                     | —                                                      |
|   <strong class="text-white font-semibold">8</strong>   | <a href="../abilities/Forest%20Sprites.md" class="text-amber-400 hover:text-amber-300 underline">Forest Sprites</a>             | <a href="../abilities/Rejuvenation%20Barrier.md" class="text-amber-400 hover:text-amber-300 underline">Rejuvenation Barrier</a> | —                                                      |
|   <strong class="text-white font-semibold">9</strong>   | <a href="../abilities/Fane%20of%20the%20Wilds.md" class="text-amber-400 hover:text-amber-300 underline">Fane of The Wilds</a>   | <a href="../abilities/Plant%20Dominion.md" class="text-amber-400 hover:text-amber-300 underline">Plant Dominion</a>             | —                                                      |
|  <strong class="text-white font-semibold">10</strong>   | <a href="../abilities/Force%20of%20Nature.md" class="text-amber-400 hover:text-amber-300 underline">Force of Nature</a>         | <a href="../abilities/Tempest.md" class="text-amber-400 hover:text-amber-300 underline">Tempest</a>                             | —                                                      |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">SPLENDOR DOMAIN</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">Level</strong> | <strong class="text-white font-semibold">Option 1</strong>                                             | <strong class="text-white font-semibold">Option 2</strong>                                                 | <strong class="text-white font-semibold">Option 3</strong>                               |
| :-------: | -------------------------------------------------------- | ------------------------------------------------------------ | ------------------------------------------ |
|   <strong class="text-white font-semibold">1</strong>   | <a href="../abilities/Bolt%20Beacon.md" class="text-amber-400 hover:text-amber-300 underline">Bolt Beacon</a>             | <a href="../abilities/Mending%20Touch.md" class="text-amber-400 hover:text-amber-300 underline">Mending Touch</a>             | <a href="../abilities/Reassurance.md" class="text-amber-400 hover:text-amber-300 underline">Reassurance</a> |
|   <strong class="text-white font-semibold">2</strong>   | <a href="../abilities/Final%20Words.md" class="text-amber-400 hover:text-amber-300 underline">Final Words</a>             | <a href="../abilities/Healing%20Hands.md" class="text-amber-400 hover:text-amber-300 underline">Healing Hands</a>             | —                                          |
|   <strong class="text-white font-semibold">3</strong>   | <a href="../abilities/Second%20Wind.md" class="text-amber-400 hover:text-amber-300 underline">Second Wind</a>             | <a href="../abilities/Voice%20of%20Reason.md" class="text-amber-400 hover:text-amber-300 underline">Voice of Reason</a>       | —                                          |
|   <strong class="text-white font-semibold">4</strong>   | <a href="../abilities/Divination.md" class="text-amber-400 hover:text-amber-300 underline">Divination</a>                 | <a href="../abilities/Life%20Ward.md" class="text-amber-400 hover:text-amber-300 underline">Life Ward</a>                     | —                                          |
|   <strong class="text-white font-semibold">5</strong>   | <a href="../abilities/Shape%20Material.md" class="text-amber-400 hover:text-amber-300 underline">Shape Material</a>       | <a href="../abilities/Smite.md" class="text-amber-400 hover:text-amber-300 underline">Smite</a>                               | —                                          |
|   <strong class="text-white font-semibold">6</strong>   | <a href="../abilities/Restoration.md" class="text-amber-400 hover:text-amber-300 underline">Restoration</a>               | <a href="../abilities/Zone%20of%20Protection.md" class="text-amber-400 hover:text-amber-300 underline">Zone of Protection</a> | —                                          |
|   <strong class="text-white font-semibold">7</strong>   | <a href="../abilities/Healing%20Strike.md" class="text-amber-400 hover:text-amber-300 underline">Healing Strike</a>       | <a href="../abilities/Splendor-Touched.md" class="text-amber-400 hover:text-amber-300 underline">Splendor-Touched</a>         | —                                          |
|   <strong class="text-white font-semibold">8</strong>   | <a href="../abilities/Shield%20Aura.md" class="text-amber-400 hover:text-amber-300 underline">Shield Aura</a>             | <a href="../abilities/Stunning%20Sunlight.md" class="text-amber-400 hover:text-amber-300 underline">Stunning Sunlight</a>     | —                                          |
|   <strong class="text-white font-semibold">9</strong>   | <a href="../abilities/Overwhelming%20Aura.md" class="text-amber-400 hover:text-amber-300 underline">Overwhelming Aura</a> | <a href="../abilities/Salvation%20Beam.md" class="text-amber-400 hover:text-amber-300 underline">Salvation Beam</a>           | —                                          |
|  <strong class="text-white font-semibold">10</strong>   | <a href="../abilities/Invigoration.md" class="text-amber-400 hover:text-amber-300 underline">Invigoration</a>             | <a href="../abilities/Resurrection.md" class="text-amber-400 hover:text-amber-300 underline">Resurrection</a>                 | —                                          |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">VALOR DOMAIN</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">Level</strong> | <strong class="text-white font-semibold">Option 1</strong>                                                   | <strong class="text-white font-semibold">Option 2</strong>                                           | <strong class="text-white font-semibold">Option 3</strong>                                               |
| :-------: | -------------------------------------------------------------- | ------------------------------------------------------ | ---------------------------------------------------------- |
|   <strong class="text-white font-semibold">1</strong>   | <a href="../abilities/Bare%20Bones.md" class="text-amber-400 hover:text-amber-300 underline">Bare Bones</a>                     | <a href="../abilities/Forceful%20Push.md" class="text-amber-400 hover:text-amber-300 underline">Forceful Push</a>       | <a href="../abilities/I%20Am%20Your%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">I Am Your Shield</a> |
|   <strong class="text-white font-semibold">2</strong>   | <a href="../abilities/Body%20Basher.md" class="text-amber-400 hover:text-amber-300 underline">Body Basher</a>                   | <a href="../abilities/Bold%20Presence.md" class="text-amber-400 hover:text-amber-300 underline">Bold Presence</a>       | —                                                          |
|   <strong class="text-white font-semibold">3</strong>   | <a href="../abilities/Critical%20Inspiration.md" class="text-amber-400 hover:text-amber-300 underline">Critical Inspiration</a> | <a href="../abilities/Lean%20on%20Me.md" class="text-amber-400 hover:text-amber-300 underline">Lean on Me</a>           | —                                                          |
|   <strong class="text-white font-semibold">4</strong>   | <a href="../abilities/Goad%20Them%20On.md" class="text-amber-400 hover:text-amber-300 underline">Goad Them On</a>               | <a href="../abilities/Support%20Tank.md" class="text-amber-400 hover:text-amber-300 underline">Support Tank</a>         | —                                                          |
|   <strong class="text-white font-semibold">5</strong>   | <a href="../abilities/Armorer.md" class="text-amber-400 hover:text-amber-300 underline">Armorer</a>                             | <a href="../abilities/Rousing%20Strike.md" class="text-amber-400 hover:text-amber-300 underline">Rousing Strike</a>     | —                                                          |
|   <strong class="text-white font-semibold">6</strong>   | <a href="../abilities/Inevitable.md" class="text-amber-400 hover:text-amber-300 underline">Inevitable</a>                       | <a href="../abilities/Rise%20Up.md" class="text-amber-400 hover:text-amber-300 underline">Rise Up</a>                   | —                                                          |
|   <strong class="text-white font-semibold">7</strong>   | <a href="../abilities/Shrug%20It%20Off.md" class="text-amber-400 hover:text-amber-300 underline">Shrug It Off</a>               | <a href="../abilities/Valor-Touched.md" class="text-amber-400 hover:text-amber-300 underline">Valor-Touched</a>         | —                                                          |
|   <strong class="text-white font-semibold">8</strong>   | <a href="../abilities/Full%20Surge.md" class="text-amber-400 hover:text-amber-300 underline">Full Surge</a>                     | <a href="../abilities/Ground%20Pound.md" class="text-amber-400 hover:text-amber-300 underline">Ground Pound</a>         | —                                                          |
|   <strong class="text-white font-semibold">9</strong>   | <a href="../abilities/Hold%20the%20Line.md" class="text-amber-400 hover:text-amber-300 underline">Hold the Line</a>             | <a href="../abilities/Lead%20by%20Example.md" class="text-amber-400 hover:text-amber-300 underline">Lead by Example</a> | —                                                          |
|  <strong class="text-white font-semibold">10</strong>   | <a href="../abilities/Unbreakable.md" class="text-amber-400 hover:text-amber-300 underline">Unbreakable</a>                     | <a href="../abilities/Unyielding%20Armor.md" class="text-amber-400 hover:text-amber-300 underline">Unyielding Armor</a> | —                                                          |</p>
