<h1 class="font-outfit text-2xl font-bold text-white border-b border-slate-700 pb-3 mb-6 mt-0">LOOT</h1>
<p class="text-slate-300 leading-relaxed mb-4"><strong class="text-white font-semibold">Loot</strong> comprises any consumables or reusable items the party acquires.</p>
<p class="text-slate-300 leading-relaxed mb-4"><strong class="text-white font-semibold">Items</strong> can be used until sold, discarded, or lost.</p>
<p class="text-slate-300 leading-relaxed mb-4">To generate a random item, choose a rarity, roll the designated dice, and match the total to the item in the table:</p>
<ul class="text-slate-300 list-disc list-inside mb-4 space-y-1">
<li class="leading-relaxed"><strong class="text-white font-semibold">Common:</strong> 1d12 or 2d12</li>
<li class="leading-relaxed"><strong class="text-white font-semibold">Uncommon:</strong> 2d12 or 3d12</li>
<li class="leading-relaxed"><strong class="text-white font-semibold">Rare:</strong> 3d12 or 4d12</li>
<li class="leading-relaxed"><strong class="text-white font-semibold">Legendary:</strong> 4d12 or 5d12</li>
</ul>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">ROLL</strong> | <strong class="text-white font-semibold">LOOT</strong>                                                                    | <strong class="text-white font-semibold">DESCRIPTION</strong>                                                                                                                                                                                                                                                                                |
| :------: | --------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|  <strong class="text-white font-semibold">1</strong>   | <a href="../items/Premium%20Bedroll.md" class="text-amber-400 hover:text-amber-300 underline">Premium Bedroll</a>                             | During downtime, you automatically clear a Stress.                                                                                                                                                                                                                                             |
|  <strong class="text-white font-semibold">2</strong>   | <a href="../items/Piper%20Whistle.md" class="text-amber-400 hover:text-amber-300 underline">Piper Whistle</a>                                 | This handcrafted whistle has a distinctive sound. When you blow this whistle, its piercing tone can be heard within a 1-mile radius.                                                                                                                                                           |
|  <strong class="text-white font-semibold">3</strong>   | <a href="../items/Charging%20Quiver.md" class="text-amber-400 hover:text-amber-300 underline">Charging Quiver</a>                             | When you succeed on an attack with an arrow stored in this quiver, gain a bonus to the damage roll equal to your current tier.                                                                                                                                                                 |
|  <strong class="text-white font-semibold">4</strong>   | <a href="../items/Alistairs%20Torch.md" class="text-amber-400 hover:text-amber-300 underline">Alistair’s Torch</a>                            | You can light this magic torch at will. The flame’s light fills a much larger space than it should, enough to illuminate a cave bright as day.                                                                                                                                                 |
|  <strong class="text-white font-semibold">5</strong>   | <a href="../items/Speaking%20Orbs.md" class="text-amber-400 hover:text-amber-300 underline">Speaking Orbs</a>                                 | This pair of orbs allows any creatures holding them to communicate with each other across any distance.                                                                                                                                                                                        |
|  <strong class="text-white font-semibold">6</strong>   | <a href="../items/Manacles.md" class="text-amber-400 hover:text-amber-300 underline">Manacles</a>                                             | This pair of locking cuffs comes with a key.                                                                                                                                                                                                                                                   |
|  <strong class="text-white font-semibold">7</strong>   | <a href="../items/Arcane%20Cloak.md" class="text-amber-400 hover:text-amber-300 underline">Arcane Cloak</a>                                   | A creature with a Spellcast trait wearing this cloak can adjust its color, texture, and size at will.                                                                                                                                                                                          |
|  <strong class="text-white font-semibold">8</strong>   | <a href="../items/Woven%20Net.md" class="text-amber-400 hover:text-amber-300 underline">Woven Net</a>                                         | You can make a Finesse Roll using this net to trap a small creature. A trapped target can break free with a successful Attack Roll (16).                                                                                                                                                       |
|  <strong class="text-white font-semibold">9</strong>   | <a href="../items/Fire%20Jar.md" class="text-amber-400 hover:text-amber-300 underline">Fire Jar</a>                                           | You can pour out the strange liquid contents of this jar to instantly produce fire. The contents regenerate when you take a long rest.                                                                                                                                                         |
|  <strong class="text-white font-semibold">10</strong>  | <a href="../items/Suspended%20Rod.md" class="text-amber-400 hover:text-amber-300 underline">Suspended Rod</a>                                 | This flat rod is inscribed with runes. When you activate the rod, it is immediately suspended in place. Until the rod is deactivated, it can’t move, doesn’t abide by the rules of gravity, and remains in place.                                                                              |
|  <strong class="text-white font-semibold">11</strong>  | <a href="../items/Glamour%20Stone.md" class="text-amber-400 hover:text-amber-300 underline">Glamour Stone</a>                                 | Activate this pebble-sized stone to memorize the appearance of someone you can see. Spend a Hope to magically recreate this guise on yourself as an illusion.                                                                                                                                  |
|  <strong class="text-white font-semibold">12</strong>  | <a href="../items/Empty%20Chest.md" class="text-amber-400 hover:text-amber-300 underline">Empty Chest</a>                                     | This magical chest appears empty. When you speak a specific trigger word or action and open the chest, you can see the items stored within it.                                                                                                                                                 |
|  <strong class="text-white font-semibold">13</strong>  | <a href="../items/Companion%20Case.md" class="text-amber-400 hover:text-amber-300 underline">Companion Case</a>                               | This case can fit a small animal companion. While the companion is inside, the animal and case are immune to all damage and harmful effects.                                                                                                                                                   |
|  <strong class="text-white font-semibold">14</strong>  | <a href="../items/Piercing%20Arrows.md" class="text-amber-400 hover:text-amber-300 underline">Piercing Arrows</a>                             | Three times per rest when you succeed on an attack with one of these arrows, you can add your Proficiency to the damage roll.                                                                                                                                                                  |
|  <strong class="text-white font-semibold">15</strong>  | <a href="../items/Valorstone.md" class="text-amber-400 hover:text-amber-300 underline">Valorstone</a>                                         | You can attach this stone to armor that doesn’t already have a feature. The armor gains the following feature. <strong class="text-white font-semibold">Resilient:</strong> Before you mark your last Armor Slot, roll a d6. On a result of 6, reduce the severity by one threshold without marking an Armor Slot.                           |
|  <strong class="text-white font-semibold">16</strong>  | <a href="../items/Skeleton%20Key.md" class="text-amber-400 hover:text-amber-300 underline">Skeleton Key</a>                                   | When you use this key to open a locked door, you gain advantage on the Finesse Roll.                                                                                                                                                                                                           |
|  <strong class="text-white font-semibold">17</strong>  | <a href="../items/Arcane%20Prism.md" class="text-amber-400 hover:text-amber-300 underline">Arcane Prism</a>                                   | Position this prism in a location of your choosing and activate it. All allies within Close range of it gain a +1 bonus to their Spellcast Rolls. While activated, the prism can’t be moved. Once the prism is deactivated, it can’t be activated again until your next long rest.             |
|  <strong class="text-white font-semibold">18</strong>  | <a href="../items/Minor%20Stamina%20Potion%20Recipe.md" class="text-amber-400 hover:text-amber-300 underline">Minor Stamina Potion Recipe</a> | As a downtime move, you can use the bone of a creature to craft a Minor Stamina Potion.                                                                                                                                                                                                        |
|  <strong class="text-white font-semibold">19</strong>  | <a href="../items/Minor%20Health%20Potion%20Recipe.md" class="text-amber-400 hover:text-amber-300 underline">Minor Health Potion Recipe</a>   | As a downtime move, you can use a vial of blood to craft a Minor Health Potion.                                                                                                                                                                                                                |
|  <strong class="text-white font-semibold">20</strong>  | <a href="../items/Homing%20Compasses.md" class="text-amber-400 hover:text-amber-300 underline">Homing Compasses</a>                           | These two compasses point toward each other no matter how far apart they are.                                                                                                                                                                                                                  |
|  <strong class="text-white font-semibold">21</strong>  | <a href="../items/Corrector%20Sprite.md" class="text-amber-400 hover:text-amber-300 underline">Corrector Sprite</a>                           | This tiny sprite sits in the curve of your ear canal and whispers helpful advice during combat. Once per short rest, you can gain advantage on an attack roll.                                                                                                                                 |
|  <strong class="text-white font-semibold">22</strong>  | <a href="../items/Gecko%20Gloves.md" class="text-amber-400 hover:text-amber-300 underline">Gecko Gloves</a>                                   | You can climb up vertical surfaces and across ceilings.                                                                                                                                                                                                                                        |
|  <strong class="text-white font-semibold">23</strong>  | <a href="../items/Lorekeeper.md" class="text-amber-400 hover:text-amber-300 underline">Lorekeeper</a>                                         | You can store the name and details of up to three hostile creatures inside this book. You gain a +1 bonus to action rolls against those creatures.                                                                                                                                             |
|  <strong class="text-white font-semibold">24</strong>  | <a href="../items/Vial%20of%20Darksmoke%20Recipe.md" class="text-amber-400 hover:text-amber-300 underline">Vial of Darksmoke Recipe</a>       | As a downtime move, you can mark a Stress to craft a Vial of Darksmoke.                                                                                                                                                                                                                        |
|  <strong class="text-white font-semibold">25</strong>  | <a href="../items/Bloodstone.md" class="text-amber-400 hover:text-amber-300 underline">Bloodstone</a>                                         | You can attach this stone to a weapon that doesn’t already have a feature. The weapon gains the following feature. <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Brutal:</strong></em> When you roll the maximum value on a damage die, roll an additional damage die.                                                                               |
|  <strong class="text-white font-semibold">26</strong>  | <a href="../items/Greatstone.md" class="text-amber-400 hover:text-amber-300 underline">Greatstone</a>                                         | You can attach this stone to a weapon that doesn’t already have a feature. The weapon gains the following feature. <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                                                        |
|  <strong class="text-white font-semibold">27</strong>  | <a href="../items/Glider.md" class="text-amber-400 hover:text-amber-300 underline">Glider</a>                                                 | While falling, you can mark a Stress to deploy this small parachute and glide safely to the ground.                                                                                                                                                                                            |
|  <strong class="text-white font-semibold">28</strong>  | <a href="../items/Ring%20of%20Silence.md" class="text-amber-400 hover:text-amber-300 underline">Ring of Silence</a>                           | Spend a Hope to activate this ring. Your footsteps are silent until your next rest.                                                                                                                                                                                                            |
|  <strong class="text-white font-semibold">29</strong>  | <a href="../items/Calming%20Pendant.md" class="text-amber-400 hover:text-amber-300 underline">Calming Pendant</a>                             | When you would mark your last Stress, roll a d6. On a result of 5 or higher, don’t mark it.                                                                                                                                                                                                    |
|  <strong class="text-white font-semibold">30</strong>  | <a href="../items/Dual%20Flask.md" class="text-amber-400 hover:text-amber-300 underline">Dual Flask</a>                                       | This flask can hold two different liquids. You can swap between them by flipping a small switch on the flask’s side.                                                                                                                                                                           |
|  <strong class="text-white font-semibold">31</strong>  | <a href="../items/Bag%20of%20Ficklesand.md" class="text-amber-400 hover:text-amber-300 underline">Bag of Ficklesand</a>                       | You can convince this small bag of sand to be much heavier or lighter with a successful Presence Roll (10). Additionally, on a successful Finesse Roll (10), you can blow a bit of sand into a target’s face to make them temporarily <strong class="text-white font-semibold">Vulnerable</strong>.                                          |
|  <strong class="text-white font-semibold">32</strong>  | <a href="../items/Ring%20of%20Resistance.md" class="text-amber-400 hover:text-amber-300 underline">Ring of Resistance</a>                     | Once per long rest, you can activate this ring after a successful attack against you to halve the damage.                                                                                                                                                                                      |
|  <strong class="text-white font-semibold">33</strong>  | <a href="../items/Phoenix%20Feather.md" class="text-amber-400 hover:text-amber-300 underline">Phoenix Feather</a>                             | If you have at least one Phoenix Feather on you when you fall unconscious, you gain a +1 bonus to the roll you make to determine whether you gain a scar.                                                                                                                                      |
|  <strong class="text-white font-semibold">34</strong>  | <a href="../items/Box%20of%20Many%20Goods.md" class="text-amber-400 hover:text-amber-300 underline">Box of Many Goods</a>                     | Once per long rest, you can open this small box and roll a d12. On a result of 1–6, it’s empty. On a result of 7–10, it contains one random common consumable. On a result of 11–12, it contains two random common consumables.                                                                |
|  <strong class="text-white font-semibold">35</strong>  | <a href="../items/Airblade%20Charm.md" class="text-amber-400 hover:text-amber-300 underline">Airblade Charm</a>                               | You can attach this charm to a weapon with a Melee range. Three times per rest, you can activate the charm and attack a target within Close range.                                                                                                                                             |
|  <strong class="text-white font-semibold">36</strong>  | <a href="../items/Portal%20Seed.md" class="text-amber-400 hover:text-amber-300 underline">Portal Seed</a>                                     | You can plant this seed in the ground to grow a portal in that spot. The portal is ready to use in 24 hours. You can use this portal to travel to any other location where you planted a portal seed. A portal can be destroyed by dealing any amount of magic damage to it.                   |
|  <strong class="text-white font-semibold">37</strong>  | <a href="../items/Paragons%20Chain.md" class="text-amber-400 hover:text-amber-300 underline">Paragon’s Chain</a>                              | As a downtime move, you can meditate on an ideal or principle you hold dear and focus your will into this chain. Once per long rest, you can spend a Hope to roll a d20 as your Hope Die for rolls that directly align with that principle.                                                    |
|  <strong class="text-white font-semibold">38</strong>  | <a href="../items/Elusive%20Amulet.md" class="text-amber-400 hover:text-amber-300 underline">Elusive Amulet</a>                               | Once per long rest, you can activate this amulet to become <strong class="text-white font-semibold">Hidden</strong> until you move. While <strong class="text-white font-semibold">Hidden</strong> in this way, you remain unseen even if an adversary moves to where they would normally see you.                                                                                         |
|  <strong class="text-white font-semibold">39</strong>  | <a href="../items/Hopekeeper%20Locket.md" class="text-amber-400 hover:text-amber-300 underline">Hopekeeper Locket</a>                         | During a long rest, if you have 6 Hope, you can spend a Hope to imbue this locket with your bountiful resolve. When you have 0 Hope, you can use the locket to immediately gain a Hope. The locket must be re-imbued before it can be used this way again.                                     |
|  <strong class="text-white font-semibold">40</strong>  | <a href="../items/Infinite%20Bag.md" class="text-amber-400 hover:text-amber-300 underline">Infinite Bag</a>                                   | When you store items in this bag, they are kept in a pocket dimension that never runs out of space. You can retrieve an item at any time.                                                                                                                                                      |
|  <strong class="text-white font-semibold">41</strong>  | <a href="../items/Stride%20Relic.md" class="text-amber-400 hover:text-amber-300 underline">Stride Relic</a>                                   | You gain a +1 bonus to your Agility. You can only carry one relic.                                                                                                                                                                                                                             |
|  <strong class="text-white font-semibold">42</strong>  | <a href="../items/Bolster%20Relic.md" class="text-amber-400 hover:text-amber-300 underline">Bolster Relic</a>                                 | You gain a +1 bonus to your Strength. You can only carry one relic.                                                                                                                                                                                                                            |
|  <strong class="text-white font-semibold">43</strong>  | <a href="../items/Control%20Relic.md" class="text-amber-400 hover:text-amber-300 underline">Control Relic</a>                                 | You gain a +1 bonus to your Finesse. You can only carry one relic.                                                                                                                                                                                                                             |
|  <strong class="text-white font-semibold">44</strong>  | <a href="../items/Attune%20Relic.md" class="text-amber-400 hover:text-amber-300 underline">Attune Relic</a>                                   | You gain a +1 bonus to your Instinct. You can only carry one relic.                                                                                                                                                                                                                            |
|  <strong class="text-white font-semibold">45</strong>  | <a href="../items/Charm%20Relic.md" class="text-amber-400 hover:text-amber-300 underline">Charm Relic</a>                                     | You gain a +1 bonus to your Presence. You can only carry one relic.                                                                                                                                                                                                                            |
|  <strong class="text-white font-semibold">46</strong>  | <a href="../items/Enlighten%20Relic.md" class="text-amber-400 hover:text-amber-300 underline">Enlighten Relic</a>                             | You gain a +1 bonus to your Knowledge. You can only carry one relic.                                                                                                                                                                                                                           |
|  <strong class="text-white font-semibold">47</strong>  | <a href="../items/Honing%20Relic.md" class="text-amber-400 hover:text-amber-300 underline">Honing Relic</a>                                   | You gain a +1 bonus to an Experience of your choice. You can only carry one relic.                                                                                                                                                                                                             |
|  <strong class="text-white font-semibold">48</strong>  | <a href="../items/Flickerfly%20Pendant.md" class="text-amber-400 hover:text-amber-300 underline">Flickerfly Pendant</a>                       | While you carry this pendant, your weapons with a Melee range that deal physical damage have a gossamer sheen and can attack targets within Very Close range.                                                                                                                                  |
|  <strong class="text-white font-semibold">49</strong>  | <a href="../items/Lasketider%20Boots.md" class="text-amber-400 hover:text-amber-300 underline">Lasketider Boots</a>                           | You can walk on the surface of water as if it were soft ground.                                                                                                                                                                                                                                |
|  <strong class="text-white font-semibold">50</strong>  | <a href="../items/Clay%20Companion.md" class="text-amber-400 hover:text-amber-300 underline">Clay Companion</a>                               | When you sculpt this ball of clay into a clay animal companion, it behaves as that animal. For example, a clay spider can spin clay webs, while a clay bird can fly. The clay companion retains memory and identity across different shapes, but they can adopt new mannerisms with each form. |
|  <strong class="text-white font-semibold">51</strong>  | <a href="../items/Mythic%20Dust%20Recipe.md" class="text-amber-400 hover:text-amber-300 underline">Mythic Dust Recipe</a>                     | As a downtime move, you can use a handful of fine gold dust to craft Mythic Dust.                                                                                                                                                                                                              |
|  <strong class="text-white font-semibold">52</strong>  | <a href="../items/Shard%20of%20Memory.md" class="text-amber-400 hover:text-amber-300 underline">Shard of Memory</a>                           | Once per long rest, you can spend 2 Hope to recall a domain card from your vault instead of paying its Recall Cost.                                                                                                                                                                            |
|  <strong class="text-white font-semibold">53</strong>  | <a href="../items/Gem%20of%20Alacrity.md" class="text-amber-400 hover:text-amber-300 underline">Gem of Alacrity</a>                           | You can attach this gem to a weapon, allowing you to use your Agility when making an attack with that weapon.                                                                                                                                                                                  |
|  <strong class="text-white font-semibold">54</strong>  | <a href="../items/Gem%20of%20Might.md" class="text-amber-400 hover:text-amber-300 underline">Gem of Might</a>                                 | You can attach this gem to a weapon, allowing you to use your Strength when making an attack with that weapon.                                                                                                                                                                                 |
|  <strong class="text-white font-semibold">55</strong>  | <a href="../items/Gem%20of%20Precision.md" class="text-amber-400 hover:text-amber-300 underline">Gem of Precision</a>                         | You can attach this gem to a weapon, allowing you to use your Finesse when making an attack with that weapon.                                                                                                                                                                                  |
|  <strong class="text-white font-semibold">56</strong>  | <a href="../items/Gem%20of%20Insight.md" class="text-amber-400 hover:text-amber-300 underline">Gem of Insight</a>                             | You can attach this gem to a weapon, allowing you to use your Instinct when making an attack with that weapon.                                                                                                                                                                                 |
|  <strong class="text-white font-semibold">57</strong>  | <a href="../items/Gem%20of%20Audacity.md" class="text-amber-400 hover:text-amber-300 underline">Gem of Audacity</a>                           | You can attach this gem to a weapon, allowing you to use your Presence when making an attack with that weapon.                                                                                                                                                                                 |
|  <strong class="text-white font-semibold">58</strong>  | <a href="../items/Gem%20of%20Sagacity.md" class="text-amber-400 hover:text-amber-300 underline">Gem of Sagacity</a>                           | You can attach this gem to a weapon, allowing you to use your Knowledge when making an attack with that weapon.                                                                                                                                                                                |
|  <strong class="text-white font-semibold">59</strong>  | <a href="../items/Ring%20of%20Unbreakable%20Resolve.md" class="text-amber-400 hover:text-amber-300 underline">Ring of Unbreakable Resolve</a> | Once per session, when the GM spends a Fear, you can spend 4 Hope to cancel the effects of that spent Fear.                                                                                                                                                                                    |
|  <strong class="text-white font-semibold">60</strong>  | <a href="../items/Belt%20of%20Unity.md" class="text-amber-400 hover:text-amber-300 underline">Belt of Unity</a>                               | Once per session, you can spend 5 Hope to lead a Tag Team Roll with three PCs instead of two.                                                                                                                                                                                                  |</p>
