<h1 class="font-outfit text-2xl font-bold text-white border-b border-slate-700 pb-3 mb-6 mt-0">PRIMARY WEAPON TABLES</h1>
<p class="text-slate-300 leading-relaxed mb-4"><em class="text-amber-300 not-italic">Players can choose one Tier 1 primary weapon during character creation. The GM can make other weapons available throughout the campaign as the PCs level up.</em></p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 1 (LEVEL 1)</h2>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">Physical Weapons</h3>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>         | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                        |
| ---------------- | --------- | ---------- | ---------- | ---------- | ------------------------------------------------------------------------------------------------------------------ |
| <a href="../weapons/Broadsword.md" class="text-amber-400 hover:text-amber-300 underline">Broadsword</a>   | Agility   | Melee      | d8 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls                                                                                 |
| <a href="../weapons/Longsword.md" class="text-amber-400 hover:text-amber-300 underline">Longsword</a>    | Agility   | Melee      | d8+3 phy   | Two-Handed | —                                                                                                                  |
| <a href="../weapons/Battleaxe.md" class="text-amber-400 hover:text-amber-300 underline">Battleaxe</a>    | Strength  | Melee      | d10+3 phy  | Two-Handed | —                                                                                                                  |
| <a href="../weapons/Greatsword.md" class="text-amber-400 hover:text-amber-300 underline">Greatsword</a>   | Strength  | Melee      | d10+3 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Massive:</strong></em> -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result. |
| <a href="../weapons/Mace.md" class="text-amber-400 hover:text-amber-300 underline">Mace</a>         | Strength  | Melee      | d8+1 phy   | One-Handed | —                                                                                                                  |
| <a href="../weapons/Warhammer.md" class="text-amber-400 hover:text-amber-300 underline">Warhammer</a>    | Strength  | Melee      | d12+3 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion                                                                                         |
| <a href="../weapons/Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Dagger</a>       | Finesse   | Melee      | d8+1 phy   | One-Handed | —                                                                                                                  |
| <a href="../weapons/Quarterstaff.md" class="text-amber-400 hover:text-amber-300 underline">Quarterstaff</a> | Instinct  | Melee      | d10+3 phy  | Two-Handed | —                                                                                                                  |
| <a href="../weapons/Cutlass.md" class="text-amber-400 hover:text-amber-300 underline">Cutlass</a>      | Presence  | Melee      | d8+1 phy   | One-Handed | —                                                                                                                  |
| <a href="../weapons/Rapier.md" class="text-amber-400 hover:text-amber-300 underline">Rapier</a>       | Presence  | Melee      | d8 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range.               |
| <a href="../weapons/Halberd.md" class="text-amber-400 hover:text-amber-300 underline">Halberd</a>      | Strength  | Very Close | d10+2 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                    |
| <a href="../weapons/Spear.md" class="text-amber-400 hover:text-amber-300 underline">Spear</a>        | Finesse   | Very Close | d10+2 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                    |
| <a href="../weapons/Shortbow.md" class="text-amber-400 hover:text-amber-300 underline">Shortbow</a>     | Agility   | Far        | d6+3 phy   | Two-Handed | —                                                                                                                  |
| <a href="../weapons/Crossbow.md" class="text-amber-400 hover:text-amber-300 underline">Crossbow</a>     | Finesse   | Far        | d6+1 phy   | One-Handed | —                                                                                                                  |
| <a href="../weapons/Longbow.md" class="text-amber-400 hover:text-amber-300 underline">Longbow</a>      | Agility   | Very Far   | d8+3 phy   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                    |</p>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">Magic Weapons</h3>
<p class="text-slate-300 leading-relaxed mb-4"><em class="text-amber-300 not-italic">All magic weapons require a Spellcast trait</em></p>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>             | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                         |
| -------------------- | --------- | ---------- | ---------- | ---------- | ------------------------------------------------------------------------------------------------------------------- |
| <a href="../weapons/Arcane%20Gauntlets.md" class="text-amber-400 hover:text-amber-300 underline">Arcane Gauntlets</a> | Strength  | Melee      | d10+3 mag  | Two-Handed | —                                                                                                                   |
| <a href="../weapons/Hallowed%20Axe.md" class="text-amber-400 hover:text-amber-300 underline">Hallowed Axe</a>     | Strength  | Melee      | d8+1 mag   | One-Handed | —                                                                                                                   |
| <a href="../weapons/Glowing%20Rings.md" class="text-amber-400 hover:text-amber-300 underline">Glowing Rings</a>    | Agility   | Very Close | d10+1 mag  | Two-Handed | —                                                                                                                   |
| <a href="../weapons/Hand%20Runes.md" class="text-amber-400 hover:text-amber-300 underline">Hand Runes</a>       | Instinct  | Very Close | d10 mag    | One-Handed | —                                                                                                                   |
| <a href="../weapons/Returning%20Blade.md" class="text-amber-400 hover:text-amber-300 underline">Returning Blade</a>  | Finesse   | Close      | d8 mag     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Returning:</strong></em> When this weapon is thrown within its range, it appears in your hand immediately after the attack. |
| <a href="../weapons/Shortstaff.md" class="text-amber-400 hover:text-amber-300 underline">Shortstaff</a>       | Instinct  | Close      | d8+1 mag   | One-Handed | —                                                                                                                   |
| <a href="../weapons/Dualstaff.md" class="text-amber-400 hover:text-amber-300 underline">Dualstaff</a>        | Instinct  | Far        | d6+3 mag   | Two-Handed | —                                                                                                                   |
| <a href="../weapons/Scepter.md" class="text-amber-400 hover:text-amber-300 underline">Scepter</a>          | Presence  | Far        | d6 mag     | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Versatile:</strong></em> This weapon can also be used with these statistics—Presence, Melee, d8.                            |
| <a href="../weapons/Wand.md" class="text-amber-400 hover:text-amber-300 underline">Wand</a>             | Knowledge | Far        | d6+1 mag   | One-Handed | —                                                                                                                   |
| <a href="../weapons/Greatstaff.md" class="text-amber-400 hover:text-amber-300 underline">Greatstaff</a>       | Knowledge | Very Far   | d6 mag     | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 2 (LEVELS 2–4)</h2>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">Physical Weapons</h3>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                  | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                                        |
| ------------------------- | --------- | ---------- | ---------- | ---------- | -------------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../weapons/Improved%20Broadsword.md" class="text-amber-400 hover:text-amber-300 underline">Improved Broadsword</a>   | Agility   | Melee      | d8+3 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls                                                                                                                 |
| <a href="../weapons/Improved%20Longsword.md" class="text-amber-400 hover:text-amber-300 underline">Improved Longsword</a>    | Agility   | Melee      | d8+6 phy   | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Improved%20Battleaxe.md" class="text-amber-400 hover:text-amber-300 underline">Improved Battleaxe</a>    | Strength  | Melee      | d10+6 phy  | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Improved%20Greatsword.md" class="text-amber-400 hover:text-amber-300 underline">Improved Greatsword</a>   | Strength  | Melee      | d10+6 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Massive:</strong></em> -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.                                 |
| <a href="../weapons/Improved%20Mace.md" class="text-amber-400 hover:text-amber-300 underline">Improved Mace</a>         | Strength  | Melee      | d8+4 phy   | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Improved%20Warhammer.md" class="text-amber-400 hover:text-amber-300 underline">Improved Warhammer</a>    | Strength  | Melee      | d12+6 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion                                                                                                                         |
| <a href="../weapons/Improved%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Improved Dagger</a>       | Finesse   | Melee      | d8+4 phy   | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Improved%20Quarterstaff.md" class="text-amber-400 hover:text-amber-300 underline">Improved Quarterstaff</a> | Instinct  | Melee      | d10+6 phy  | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Improved%20Cutlass.md" class="text-amber-400 hover:text-amber-300 underline">Improved Cutlass</a>      | Presence  | Melee      | d8+4 phy   | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Improved%20Rapier.md" class="text-amber-400 hover:text-amber-300 underline">Improved Rapier</a>       | Presence  | Melee      | d8+3 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range.                                               |
| <a href="../weapons/Improved%20Halberd.md" class="text-amber-400 hover:text-amber-300 underline">Improved Halberd</a>      | Strength  | Very Close | d10+5 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                                                    |
| <a href="../weapons/Improved%20Spear.md" class="text-amber-400 hover:text-amber-300 underline">Improved Spear</a>        | Finesse   | Very Close | d10+5 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                                                    |
| <a href="../weapons/Improved%20Shortbow.md" class="text-amber-400 hover:text-amber-300 underline">Improved Shortbow</a>     | Agility   | Far        | d6+6 phy   | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Improved%20Crossbow.md" class="text-amber-400 hover:text-amber-300 underline">Improved Crossbow</a>     | Finesse   | Far        | d6+4 phy   | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Improved%20Longbow.md" class="text-amber-400 hover:text-amber-300 underline">Improved Longbow</a>      | Agility   | Very Far   | d8+6 phy   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                                                    |
| <a href="../weapons/Gilded%20Falchion.md" class="text-amber-400 hover:text-amber-300 underline">Gilded Falchion</a>       | Strength  | Melee      | d10+4 phy  | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                               |
| <a href="../weapons/Knuckle%20Blades.md" class="text-amber-400 hover:text-amber-300 underline">Knuckle Blades</a>        | Strength  | Melee      | d10+6 phy  | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Brutal:</strong></em> When you roll the maximum value on a damage die, roll an additional damage die.                                                      |
| <a href="../weapons/Urok%20Broadsword.md" class="text-amber-400 hover:text-amber-300 underline">Urok Broadsword</a>       | Finesse   | Melee      | d8+3 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Deadly:</strong></em> When you deal Severe damage, the target must mark an additional HP.                                                                  |
| <a href="../weapons/Bladed%20Whip.md" class="text-amber-400 hover:text-amber-300 underline">Bladed Whip</a>           | Agility   | Very Close | d8+3 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range.                                               |
| <a href="../weapons/Steelforged%20Halberd.md" class="text-amber-400 hover:text-amber-300 underline">Steelforged Halberd</a>   | Strength  | Very Close | d8+4 phy   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Scary:</strong></em> On a successful attack, the target must mark a Stress.                                                                                |
| <a href="../weapons/War%20Scythe.md" class="text-amber-400 hover:text-amber-300 underline">War Scythe</a>            | Finesse   | Very Close | d8+5 phy   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls                                                                                                                 |
| <a href="../weapons/Blunderbuss.md" class="text-amber-400 hover:text-amber-300 underline">Blunderbuss</a>           | Finesse   | Close      | d8+6 phy   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reloading:</strong></em> After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again. |
| <a href="../weapons/Greatbow.md" class="text-amber-400 hover:text-amber-300 underline">Greatbow</a>              | Strength  | Far        | d6+6 phy   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                               |
| <a href="../weapons/Finehair%20Bow.md" class="text-amber-400 hover:text-amber-300 underline">Finehair Bow</a>          | Agility   | Very Far   | d6+5 phy   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls                                                                                                                 |</p>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">Magic Weapons</h3>
<p class="text-slate-300 leading-relaxed mb-4"><em class="text-amber-300 not-italic">All magic weapons require a Spellcast trait</em></p>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                                                                 | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                                                                         |
| ------------------------------------------------------------------------ | --------- | ---------- | ---------- | ---------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../weapons/Improved%20Arcane%20Gauntlets.md" class="text-amber-400 hover:text-amber-300 underline">Improved Arcane Gauntlets</a> | Strength  | Melee      | d10+6 mag  | Two-Handed | —                                                                                                                                                                                   |
| <a href="../weapons/Improved%20Hallowed%20Axe.md" class="text-amber-400 hover:text-amber-300 underline">Improved Hallowed Axe</a>         | Strength  | Melee      | d8+4 mag   | One-Handed | —                                                                                                                                                                                   |
| <a href="../weapons/Improved%20Glowing%20Rings.md" class="text-amber-400 hover:text-amber-300 underline">Improved Glowing Rings</a>       | Agility   | Very Close | d10+5 mag  | Two-Handed | —                                                                                                                                                                                   |
| <a href="../weapons/Improved%20Hand%20Runes.md" class="text-amber-400 hover:text-amber-300 underline">Improved Hand Runes</a>             | Instinct  | Very Close | d10+3 mag  | One-Handed | —                                                                                                                                                                                   |
| <a href="../weapons/Improved%20Returning%20Blade.md" class="text-amber-400 hover:text-amber-300 underline">Improved Returning Blade</a>   | Finesse   | Close      | d8+3 mag   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Returning:</strong></em> When this weapon is thrown within its range, it appears in your hand immediately after the attack.                                                                 |
| <a href="../weapons/Improved%20Shortstaff.md" class="text-amber-400 hover:text-amber-300 underline">Improved Shortstaff</a>               | Instinct  | Close      | d8+4 mag   | One-Handed | —                                                                                                                                                                                   |
| <a href="../weapons/Improved%20Dualstaff.md" class="text-amber-400 hover:text-amber-300 underline">Improved Dualstaff</a>                 | Instinct  | Far        | d6+6 mag   | Two-Handed | —                                                                                                                                                                                   |
| <a href="../weapons/Improved%20Scepter.md" class="text-amber-400 hover:text-amber-300 underline">Improved Scepter</a>                     | Presence  | Far        | d6+3 mag   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Versatile:</strong></em> This weapon can also be used with these statistics—Presence, Melee, d8+3.                                                                                          |
| <a href="../weapons/Improved%20Wand.md" class="text-amber-400 hover:text-amber-300 underline">Improved Wand</a>                           | Knowledge | Far        | d6+4 mag   | One-Handed | —                                                                                                                                                                                   |
| <a href="../weapons/Improved%20Greatstaff.md" class="text-amber-400 hover:text-amber-300 underline">Improved Greatstaff</a>               | Knowledge | Very Far   | d6+3 mag   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                                                                |
| <a href="../weapons/Ego%20Blade.md" class="text-amber-400 hover:text-amber-300 underline">Ego Blade</a>                                   | Agility   | Melee      | d12+4 mag  | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Pompous:</strong></em> You must have a Presence of 0 or lower to use this weapon.                                                                                                           |
| <a href="../weapons/Casting%20Sword.md" class="text-amber-400 hover:text-amber-300 underline">Casting Sword</a>                           | Strength  | Melee      | d10+4 mag  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Versatile:</strong></em> This weapon can also be used with these statistics—Knowledge, Far, d6+3.                                                                                           |
| <a href="../weapons/Devouring%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Devouring Dagger</a>                     | Finesse   | Melee      | d8+4 mag   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Scary:</strong></em> On a successful attack, the target must mark a Stress.                                                                                                                 |
| <a href="../weapons/Hammer%20of%20Exota.md" class="text-amber-400 hover:text-amber-300 underline">Hammer of Exota</a>                     | Instinct  | Melee      | d8+6 mag   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Eruptive:</strong></em> On a successful attack against a target within Melee range, all other adversaries within Very Close range must succeed on a reaction roll (14) or take half damage. |
| <a href="../weapons/Yutari%20Bloodbow.md" class="text-amber-400 hover:text-amber-300 underline">Yutari Bloodbow</a>                       | Finesse   | Far        | d6+4 mag   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Brutal:</strong></em> When you roll the maximum value on a damage die, roll an additional damage die.                                                                                       |
| <a href="../weapons/Elder%20Bow.md" class="text-amber-400 hover:text-amber-300 underline">Elder Bow</a>                                   | Instinct  | Far        | d6+4 mag   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                                                                |
| <a href="../weapons/Scepter%20of%20Elias.md" class="text-amber-400 hover:text-amber-300 underline">Scepter of Elias</a>                   | Presence  | Far        | d6+3 mag   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Invigorating:</strong></em> On a successful attack, roll a d4. On a result of 4, clear a Stress.                                                                                            |
| <a href="../weapons/Wand%20of%20Enthrallment.md" class="text-amber-400 hover:text-amber-300 underline">Wand of Enthrallment</a>           | Presence  | Far        | d6+4 mag   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Persuasive:</strong></em> Before you make a Presence Roll, you can mark a Stress to gain a +2 bonus to the result.                                                                          |
| <a href="../weapons/Keepers%20Staff.md" class="text-amber-400 hover:text-amber-300 underline">Keeper’s Staff</a>                          | Knowledge | Far        | d6+4 mag   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls                                                                                                                                                  |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 3 (LEVELS 5–7)</h2>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">Physical Weapons</h3>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                  | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                                        |
| ------------------------- | --------- | ---------- | ---------- | ---------- | -------------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../weapons/Advanced%20Broadsword.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Broadsword</a>   | Agility   | Melee      | d8+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls                                                                                                                 |
| <a href="../weapons/Advanced%20Longsword.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Longsword</a>    | Agility   | Melee      | d8+9 phy   | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Battleaxe.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Battleaxe</a>    | Strength  | Melee      | d10+9 phy  | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Greatsword.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Greatsword</a>   | Strength  | Melee      | d10+9 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Massive:</strong></em> -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.                                 |
| <a href="../weapons/Advanced%20Mace.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Mace</a>         | Strength  | Melee      | d8+7 phy   | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Warhammer.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Warhammer</a>    | Strength  | Melee      | d12+9 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion                                                                                                                         |
| <a href="../weapons/Advanced%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Dagger</a>       | Finesse   | Melee      | d8+7 phy   | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Quarterstaff.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Quarterstaff</a> | Instinct  | Melee      | d10+9 phy  | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Cutlass.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Cutlass</a>      | Presence  | Melee      | d8+7 phy   | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Rapier.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Rapier</a>       | Presence  | Melee      | d8+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range.                                               |
| <a href="../weapons/Advanced%20Halberd.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Halberd</a>      | Strength  | Very Close | d10+8 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                                                    |
| <a href="../weapons/Advanced%20Spear.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Spear</a>        | Finesse   | Very Close | d10+8 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                                                    |
| <a href="../weapons/Advanced%20Shortbow.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Shortbow</a>     | Agility   | Far        | d6+9 phy   | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Crossbow.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Crossbow</a>     | Finesse   | Far        | d6+7 phy   | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Longbow.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Longbow</a>      | Agility   | Very Far   | d8+9 phy   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                                                    |
| <a href="../weapons/Flickerfly%20Blade.md" class="text-amber-400 hover:text-amber-300 underline">Flickerfly Blade</a>      | Agility   | Melee      | d8+5 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Sharpening:</strong></em> Gain a bonus to your damage rolls equal to your Agility.                                                                         |
| <a href="../weapons/Bravesword.md" class="text-amber-400 hover:text-amber-300 underline">Bravesword</a>            | Strength  | Melee      | d12+7 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Brave:</strong></em> -1 to Evasion; +3 to Severe damage threshold                                                                                          |
| <a href="../weapons/Hammer%20of%20Wrath.md" class="text-amber-400 hover:text-amber-300 underline">Hammer of Wrath</a>       | Strength  | Melee      | d10+7 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Devastating:</strong></em> Before you make an attack roll, you can mark a Stress to use a d20 as your damage die.                                          |
| <a href="../weapons/Labrys%20Axe.md" class="text-amber-400 hover:text-amber-300 underline">Labrys Axe</a>            | Strength  | Melee      | d10+7 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Protective:</strong></em> +1 to Armor Score                                                                                                                |
| <a href="../weapons/Meridian%20Cutlass.md" class="text-amber-400 hover:text-amber-300 underline">Meridian Cutlass</a>      | Presence  | Melee      | d10+5 phy  | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Dueling:</strong></em> When there are no other creatures within Close range of the target, gain advantage on your attack roll against them.                |
| <a href="../weapons/Retractable%20Saber.md" class="text-amber-400 hover:text-amber-300 underline">Retractable Saber</a>     | Presence  | Melee      | d10+7 phy  | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Retractable:</strong></em> The blade can be hidden in the hilt to avoid detection.                                                                         |
| <a href="../weapons/Double%20Flail.md" class="text-amber-400 hover:text-amber-300 underline">Double Flail</a>          | Agility   | Very Close | d10+8 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                               |
| <a href="../weapons/Talon%20Blades.md" class="text-amber-400 hover:text-amber-300 underline">Talon Blades</a>          | Finesse   | Close      | d10+7 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Brutal:</strong></em> When you roll the maximum value on a damage die, roll an additional damage die.                                                      |
| <a href="../weapons/Black%20Powder%20Revolver.md" class="text-amber-400 hover:text-amber-300 underline">Black Powder Revolver</a> | Finesse   | Far        | d6+8 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reloading:</strong></em> After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again. |
| <a href="../weapons/Spiked%20Bow.md" class="text-amber-400 hover:text-amber-300 underline">Spiked Bow</a>            | Agility   | Very Far   | d6+7 phy   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Versatile:</strong></em> This weapon can also be used with these statistics—Agility, Melee, d10+5.                                                         |</p>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">Magic Weapons</h3>
<p class="text-slate-300 leading-relaxed mb-4"><em class="text-amber-300 not-italic">All magic weapons require a Spellcast trait</em></p>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                                                                 | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong>       | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                                        |
| :----------------------------------------------------------------------- | :-------- | :--------- | :--------------- | :--------- | :------------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../weapons/Advanced%20Arcane%20Gauntlets.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Arcane Gauntlets</a> | Strength  | Melee      | d10+9 mag        | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Hallowed%20Axe.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Hallowed Axe</a>         | Strength  | Melee      | d8+7 mag         | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Glowing%20Rings.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Glowing Rings</a>       | Agility   | Very Close | d10+8 mag        | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Hand%20Runes.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Hand Runes</a>             | Instinct  | Very Close | d10+6 mag        | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Returning%20Blade.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Returning Blade</a>   | Finesse   | Close      | d8+6 mag         | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Returning:</strong></em> When this weapon is thrown within its range, it appears in your hand immediately after the attack.                                |
| <a href="../weapons/Advanced%20Shortstaff.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Shortstaff</a>               | Instinct  | Close      | d8+7 mag         | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Dualstaff.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Dualstaff</a>                 | Instinct  | Far        | d6+9 mag         | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Scepter.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Scepter</a>                     | Presence  | Far        | d6+6 mag         | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Versatile:</strong></em> This weapon can also be used with these statistics—Presence, Melee, d8+4.                                                         |
| <a href="../weapons/Advanced%20Wand.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Wand</a>                           | Knowledge | Far        | d6+7 mag         | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Advanced%20Greatstaff.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Greatstaff</a>               | Knowledge | Very Far   | d6+6 mag         | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                               |
| <a href="../weapons/Axe%20of%20Fortunis.md" class="text-amber-400 hover:text-amber-300 underline">Axe of Fortunis</a>                     | Strength  | Melee      | d10+8 mag        | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Lucky:</strong></em> On a failed attack, you can mark a Stress to reroll your attack.                                                                      |
| <a href="../weapons/Blessed%20Anlace.md" class="text-amber-400 hover:text-amber-300 underline">Blessed Anlace</a>                         | Instinct  | Melee      | d10+6 mag        | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Healing:</strong></em> During downtime, automatically clear a Hit Point.                                                                                   |
| <a href="../weapons/Ghostblade.md" class="text-amber-400 hover:text-amber-300 underline">Ghostblade</a>                                   | Presence  | Melee      | d10+7 phy or mag | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Otherworldly:</strong></em> On a successful attack, you can deal physical or magic damage.                                                                 |
| <a href="../weapons/Runes%20of%20Ruination.md" class="text-amber-400 hover:text-amber-300 underline">Runes of Ruination</a>               | Knowledge | Very Close | d20+4 mag        | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Painful:</strong></em> Each time you make a successful attack, you must mark a Stress.                                                                     |
| <a href="../weapons/Widgast%20Pendant.md" class="text-amber-400 hover:text-amber-300 underline">Widgast Pendant</a>                       | Knowledge | Close      | d10+5 mag        | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Timebending:</strong></em> You choose the target of your attack after making your attack roll.                                                             |
| <a href="../weapons/Gilded%20Bow.md" class="text-amber-400 hover:text-amber-300 underline">Gilded Bow</a>                                 | Finesse   | Far        | d6+7 mag         | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Self-Correcting:</strong></em> When you roll a 1 on a damage die, it deals 6 damage instead.                                                               |
| <a href="../weapons/Firestaff.md" class="text-amber-400 hover:text-amber-300 underline">Firestaff</a>                                     | Instinct  | Far        | d6+7 mag         | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Burning:</strong></em> When you roll a 6 on a damage die, the target must mark a Stress.                                                                   |
| <a href="../weapons/Mage%20Orb.md" class="text-amber-400 hover:text-amber-300 underline">Mage Orb</a>                                     | Knowledge | Far        | d6+7 mag         | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                               |
| <a href="../weapons/Ilmaris%20Rifle.md" class="text-amber-400 hover:text-amber-300 underline">Ilmari's Rifle</a>                          | Finesse   | Very Far   | d6+6 mag         | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reloading:</strong></em> After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again. |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 4 (LEVELS 8–10)</h2>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">Physical Weapons</h3>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                   | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                              |
| -------------------------- | --------- | ---------- | ---------- | ---------- | ---------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../weapons/Legendary%20Broadsword.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Broadsword</a>   | Agility   | Melee      | d8+9 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls                                                                                                       |
| <a href="../weapons/Legendary%20Longsword.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Longsword</a>    | Agility   | Melee      | d8+12 phy  | Two-Handed | —                                                                                                                                        |
| <a href="../weapons/Legendary%20Battleaxe.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Battleaxe</a>    | Strength  | Melee      | d10+12 phy | Two-Handed | —                                                                                                                                        |
| <a href="../weapons/Legendary%20Greatsword.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Greatsword</a>   | Strength  | Melee      | d10+12 phy | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Massive:</strong></em> -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.                       |
| <a href="../weapons/Legendary%20Mace.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Mace</a>         | Strength  | Melee      | d8+10 phy  | One-Handed | —                                                                                                                                        |
| <a href="../weapons/Legendary%20Warhammer.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Warhammer</a>    | Strength  | Melee      | d12+12 phy | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Heavy:</strong></em> -1 to Evasion                                                                                                               |
| <a href="../weapons/Legendary%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Dagger</a>       | Finesse   | Melee      | d8+10 phy  | One-Handed | —                                                                                                                                        |
| <a href="../weapons/Legendary%20Quarterstaff.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Quarterstaff</a> | Instinct  | Melee      | d10+12 phy | Two-Handed | —                                                                                                                                        |
| <a href="../weapons/Legendary%20Cutlass.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Cutlass</a>      | Presence  | Melee      | d8+10 phy  | One-Handed | —                                                                                                                                        |
| <a href="../weapons/Legendary%20Rapier.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Rapier</a>       | Presence  | Melee      | d8+9 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range.                                     |
| <a href="../weapons/Legendary%20Halberd.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Halberd</a>      | Strength  | Very Close | d10+11 phy | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                                          |
| <a href="../weapons/Legendary%20Spear.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Spear</a>        | Finesse   | Very Close | d10+11 phy | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                                          |
| <a href="../weapons/Legendary%20Shortbow.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Shortbow</a>     | Agility   | Far        | d6+12 phy  | Two-Handed | —                                                                                                                                        |
| <a href="../weapons/Legendary%20Crossbow.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Crossbow</a>     | Finesse   | Far        | d6+10 phy  | One-Handed | —                                                                                                                                        |
| <a href="../weapons/Legendary%20Longbow.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Longbow</a>      | Agility   | Very Far   | d8+12 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Cumbersome:</strong></em> -1 to Finesse                                                                                                          |
| <a href="../weapons/Dual-Ended%20Sword.md" class="text-amber-400 hover:text-amber-300 underline">Dual-Ended Sword</a>       | Agility   | Melee      | d10+9 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Quick:</strong></em> When you make an attack, you can mark a Stress to target another creature within range.                                     |
| <a href="../weapons/Impact%20Gauntlet.md" class="text-amber-400 hover:text-amber-300 underline">Impact Gauntlet</a>        | Strength  | Melee      | d10+11 phy | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Concussive:</strong></em> On a successful attack, you can spend a Hope to knock the target back to Far range.                                    |
| <a href="../weapons/Sledge%20Axe.md" class="text-amber-400 hover:text-amber-300 underline">Sledge Axe</a>             | Strength  | Melee      | d12+13 phy | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Destructive:</strong></em> -1 to Agility; on a successful attack, all adversaries within Very Close range must mark a Stress.                    |
| <a href="../weapons/Curved%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Curved Dagger</a>          | Finesse   | Melee      | d8+9 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Serrated:</strong></em> When you roll a 1 on a damage die, it deals 8 damage instead.                                                            |
| <a href="../weapons/Extended%20Polearm.md" class="text-amber-400 hover:text-amber-300 underline">Extended Polearm</a>       | Finesse   | Very Close | d8+10 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Long:</strong></em> This weapon’s attack targets all adversaries in a line within range.                                                         |
| <a href="../weapons/Swinging%20Ropeblade.md" class="text-amber-400 hover:text-amber-300 underline">Swinging Ropeblade</a>     | Presence  | Close      | d8+9 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Grappling:</strong></em> On a successful attack, you can spend a Hope to Restrain the target or pull them into Melee range with you.             |
| <a href="../weapons/Ricochet%20Axes.md" class="text-amber-400 hover:text-amber-300 underline">Ricochet Axes</a>          | Agility   | Far        | d6+11 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Bouncing:</strong></em> Mark 1 or more Stress to hit that many targets in range of the attack.                                                   |
| <a href="../weapons/Aantari%20Bow.md" class="text-amber-400 hover:text-amber-300 underline">Aantari Bow</a>            | Finesse   | Far        | d6+11 phy  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls                                                                                                       |
| <a href="../weapons/Hand%20Cannon.md" class="text-amber-400 hover:text-amber-300 underline">Hand Cannon</a>            | Finesse   | Very Far   | d6+12 phy  | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reloading:</strong></em> After you make an attack, roll a d6. On a 1, you must mark a Stress to reload this weapon before you can fire it again. |</p>
<h3 class="font-outfit text-lg font-bold text-amber-300 mt-6 mb-3">Magic Weapons</h3>
<p class="text-slate-300 leading-relaxed mb-4"><em class="text-amber-300 not-italic">All magic weapons require a Spellcast trait</em></p>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                                                                   | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                                        |
| -------------------------------------------------------------------------- | --------- | ---------- | ---------- | ---------- | -------------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../weapons/Legendary%20Arcane%20Gauntlets.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Arcane Gauntlets</a> | Strength  | Melee      | d10+12 mag | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Legendary%20Hallowed%20Axe.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Hallowed Axe</a>         | Strength  | Melee      | d8+10 mag  | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Legendary%20Glowing%20Rings.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Glowing Rings</a>       | Agility   | Very Close | d10+11 mag | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Legendary%20Hand%20Runes.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Hand Runes</a>             | Instinct  | Very Close | d10+9 mag  | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Legendary%20Returning%20Blade.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Returning Blade</a>   | Finesse   | Close      | d8+9 mag   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Returning:</strong></em> When this weapon is thrown within its range, it appears in your hand immediately after the attack.                                |
| <a href="../weapons/Legendary%20Shortstaff.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Shortstaff</a>               | Instinct  | Close      | d8+10 mag  | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Legendary%20Dualstaff.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Dualstaff</a>                 | Instinct  | Far        | d8+12 mag  | Two-Handed | —                                                                                                                                                  |
| <a href="../weapons/Legendary%20Scepter.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Scepter</a>                     | Presence  | Far        | d6+9 mag   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Versatile:</strong></em> This weapon can also be used with these statistics—Presence, Melee, d8+6.                                                         |
| <a href="../weapons/Legendary%20Wand.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Wand</a>                           | Knowledge | Far        | d6+10 mag  | One-Handed | —                                                                                                                                                  |
| <a href="../weapons/Legendary%20Greatstaff.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Greatstaff</a>               | Knowledge | Very Far   | d6+9 mag   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                               |
| <a href="../weapons/Sword%20of%20Light%20and%20Flame.md" class="text-amber-400 hover:text-amber-300 underline">Sword of Light and Flame</a>     | Strength  | Melee      | d10+11 mag | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Hot:</strong></em> This weapon cuts through solid material.                                                                                                |
| <a href="../weapons/Siphoning%20Gauntlets.md" class="text-amber-400 hover:text-amber-300 underline">Siphoning Gauntlets</a>                 | Presence  | Melee      | d10+9 mag  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Lifestealing:</strong></em> On a successful attack, roll a d6. On a result of 6, clear a Hit Point or clear a Stress.                                      |
| <a href="../weapons/Midas%20Scythe.md" class="text-amber-400 hover:text-amber-300 underline">Midas Scythe</a>                               | Knowledge | Melee      | d10+9 mag  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Greedy:</strong></em> Spend a handful of gold to gain a +1 bonus to your Proficiency on a damage roll.                                                     |
| <a href="../weapons/Floating%20Bladeshards.md" class="text-amber-400 hover:text-amber-300 underline">Floating Bladeshards</a>               | Instinct  | Close      | d8+9 mag   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Powerful:</strong></em> On a successful attack, roll an additional damage die and discard the lowest result.                                               |
| <a href="../weapons/Bloodstaff.md" class="text-amber-400 hover:text-amber-300 underline">Bloodstaff</a>                                     | Instinct  | Far        | d20+7 mag  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Painful:</strong></em> Each time you make a successful attack, you must mark a Stress.                                                                     |
| <a href="../weapons/Thistlebow.md" class="text-amber-400 hover:text-amber-300 underline">Thistlebow</a>                                     | Instinct  | Far        | d6+13 mag  | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reliable:</strong></em> +1 to attack rolls                                                                                                                 |
| <a href="../weapons/Wand%20of%20Essek.md" class="text-amber-400 hover:text-amber-300 underline">Wand of Essek</a>                           | Knowledge | Far        | d8+13 mag  | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Timebending:</strong></em> You can choose the target of your attack after making your attack roll.                                                         |
| <a href="../weapons/Magus%20Revolver.md" class="text-amber-400 hover:text-amber-300 underline">Magus Revolver</a>                           | Finesse   | Very Far   | d6+13 mag  | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Reloading:</strong></em> After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again. |
| <a href="../weapons/Fusion%20Gloves.md" class="text-amber-400 hover:text-amber-300 underline">Fusion Gloves</a>                             | Knowledge | Very Far   | d6+9 mag   | Two-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Bonded:</strong></em> Gain a bonus to your damage rolls equal to your level.                                                                               |</p>
