<h1 class="font-outfit text-2xl font-bold text-white border-b border-slate-700 pb-3 mb-6 mt-0">SECONDARY WEAPON TABLES</h1>
<p class="text-slate-300 leading-relaxed mb-4"><em class="text-amber-300 not-italic">Players can choose one Tier 1 secondary weapon during character creation. The GM can make other weapons available throughout the campaign as the PCs level up.</em></p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 1 (LEVEL 1)</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>          | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                        |
| ----------------- | --------- | ---------- | ---------- | ---------- | ------------------------------------------------------------------------------------------------------------------ |
| <a href="../weapons/Shortsword.md" class="text-amber-400 hover:text-amber-300 underline">Shortsword</a>    | Agility   | Melee      | d8 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Paired:</strong></em> +2 to primary weapon damage to targets within Melee range                                            |
| <a href="../weapons/Round%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">Round Shield</a>  | Strength  | Melee      | d4 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Protective:</strong></em> +1 to Armor Score                                                                                |
| <a href="../weapons/Tower%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">Tower Shield</a>  | Strength  | Melee      | d6 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Barrier:</strong></em> +2 to Armor Score; -1 to Evasion                                                                    |
| <a href="../weapons/Small%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Small Dagger</a>  | Finesse   | Melee      | d8 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Paired:</strong></em> +2 to primary weapon damage to targets within Melee range                                            |
| <a href="../weapons/Whip.md" class="text-amber-400 hover:text-amber-300 underline">Whip</a>          | Presence  | Very Close | d6 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Startling:</strong></em> Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range. |
| <a href="../weapons/Grappler.md" class="text-amber-400 hover:text-amber-300 underline">Grappler</a>      | Finesse   | Close      | d6 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Hooked:</strong></em> On a successful attack, you can pull the target into Melee range.                                    |
| <a href="../weapons/Hand%20Crossbow.md" class="text-amber-400 hover:text-amber-300 underline">Hand Crossbow</a> | Finesse   | Far        | d6+1 phy   | One-Handed | —                                                                                                                  |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 2 (LEVELS 2–4)</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                   | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                                                                                                                                            |
| -------------------------- | --------- | ---------- | ---------- | ---------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| <a href="../weapons/Improved%20Shortsword.md" class="text-amber-400 hover:text-amber-300 underline">Improved Shortsword</a>    | Agility   | Melee      | d8+2 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Paired:</strong></em> +3 to primary weapon damage to targets within Melee range                                                                                                                                                                                |
| <a href="../weapons/Improved%20Round%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">Improved Round Shield</a>  | Strength  | Melee      | d4+2 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Protective:</strong></em> +2 to Armor Score                                                                                                                                                                                                                    |
| <a href="../weapons/Improved%20Tower%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">Improved Tower Shield</a>  | Strength  | Melee      | d6+2 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Barrier:</strong></em> +3 to Armor Score; -1 to Evasion                                                                                                                                                                                                        |
| <a href="../weapons/Improved%20Small%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Improved Small Dagger</a>  | Finesse   | Melee      | d8+2 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Paired:</strong></em> +3 to primary weapon damage to targets within Melee range                                                                                                                                                                                |
| <a href="../weapons/Improved%20Whip.md" class="text-amber-400 hover:text-amber-300 underline">Improved Whip</a>          | Presence  | Very Close | d6+2 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Startling:</strong></em> Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.                                                                                                                                     |
| <a href="../weapons/Improved%20Grappler.md" class="text-amber-400 hover:text-amber-300 underline">Improved Grappler</a>      | Finesse   | Close      | d6+2 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Hooked:</strong></em> On a successful attack, you can pull the target into Melee range.                                                                                                                                                                        |
| <a href="../weapons/Improved%20Hand%20Crossbow.md" class="text-amber-400 hover:text-amber-300 underline">Improved Hand Crossbow</a> | Finesse   | Far        | d6+3 phy   | One-Handed | —                                                                                                                                                                                                                                                      |
| <a href="../weapons/Spiked%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">Spiked Shield</a>          | Strength  | Melee      | d6+2 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Double Duty:</strong></em> +1 to Armor Score; +1 to primary weapon damage within Melee range                                                                                                                                                                   |
| <a href="../weapons/Parrying%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Parrying Dagger</a>        | Finesse   | Melee      | d6+2 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Parry:</strong></em> When you are attacked, roll this weapon’s damage dice. If any of the attacker’s damage dice rolled the same value as your dice, the matching results are discarded from the attacker’s damage dice before the damage you take is totaled. |
| <a href="../weapons/Returning%20Axe.md" class="text-amber-400 hover:text-amber-300 underline">Returning Axe</a>          | Agility   | Close      | d6+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Returning:</strong></em> When this weapon is thrown within its range, it appears in your hand immediately after the attack.                                                                                                                                    |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 3 (LEVELS 5–7)</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                   | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                                       |
| -------------------------- | --------- | ---------- | ---------- | ---------- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../weapons/Advanced%20Shortsword.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Shortsword</a>    | Agility   | Melee      | d8+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Paired:</strong></em> +4 to primary weapon damage to targets within Melee range                                                                           |
| <a href="../weapons/Advanced%20Round%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Round Shield</a>  | Strength  | Melee      | d4+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Protective:</strong></em> +3 to Armor Score                                                                                                               |
| <a href="../weapons/Advanced%20Tower%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Tower Shield</a>  | Strength  | Melee      | d6+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Barrier:</strong></em> +4 to Armor Score; –1 to Evasion                                                                                                   |
| <a href="../weapons/Advanced%20Small%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Small Dagger</a>  | Finesse   | Melee      | d8+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Paired:</strong></em> +4 to primary weapon damage to targets within Melee range                                                                           |
| <a href="../weapons/Advanced%20Whip.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Whip</a>          | Presence  | Very Close | d6+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Startling:</strong></em> Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.                                |
| <a href="../weapons/Advanced%20Grappler.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Grappler</a>      | Finesse   | Close      | d6+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Hooked:</strong></em> On a successful attack, you can pull the target into Melee range.                                                                   |
| <a href="../weapons/Advanced%20Hand%20Crossbow.md" class="text-amber-400 hover:text-amber-300 underline">Advanced Hand Crossbow</a> | Finesse   | Far        | d6+5 phy   | One-Handed | —                                                                                                                                                 |
| <a href="../weapons/Buckler.md" class="text-amber-400 hover:text-amber-300 underline">Buckler</a>                | Agility   | Melee      | d4+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Deflecting:</strong></em> When you are attacked, you can mark an Armor Slot to gain a bonus to your Evasion equal to your Armor Score against the attack. |
| <a href="../weapons/Powered%20Gauntlet.md" class="text-amber-400 hover:text-amber-300 underline">Powered Gauntlet</a>       | Knowledge | Close      | d6+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Charged:</strong></em> Mark a Stress to gain a +1 bonus to your Proficiency on a primary weapon attack.                                                   |
| <a href="../weapons/Hand%20Sling.md" class="text-amber-400 hover:text-amber-300 underline">Hand Sling</a>             | Finesse   | Very Close | d6+4 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Versatile:</strong></em> This weapon can also be used with these statistics—Finesse, Close, d8+4.                                                         |</p>
<h2 class="font-outfit text-xl font-bold text-amber-400 mt-8 mb-4">TIER 4 (LEVELS 8–10)</h2>
<p class="text-slate-300 leading-relaxed mb-4">| <strong class="text-white font-semibold">NAME</strong>                    | <strong class="text-white font-semibold">TRAIT</strong> | <strong class="text-white font-semibold">RANGE</strong>  | <strong class="text-white font-semibold">DAMAGE</strong> | <strong class="text-white font-semibold">BURDEN</strong> | <strong class="text-white font-semibold">FEATURE</strong>                                                                                                                                 |
| --------------------------- | --------- | ---------- | ---------- | ---------- | ------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../weapons/Legendary%20Shortsword.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Shortsword</a>    | Agility   | Melee      | d8+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Paired:</strong></em> +5 to primary weapon damage to targets within Melee range                                                                     |
| <a href="../weapons/Legendary%20Round%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Round Shield</a>  | Strength  | Melee      | d4+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Protective:</strong></em> +4 to Armor Score                                                                                                         |
| <a href="../weapons/Legendary%20Tower%20Shield.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Tower Shield</a>  | Strength  | Melee      | d6+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Barrier:</strong></em> +5 to Armor Score; –1 to Evasion.                                                                                            |
| <a href="../weapons/Legendary%20Small%20Dagger.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Small Dagger</a>  | Finesse   | Melee      | d8+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Paired:</strong></em> +5 to primary weapon damage to targets within Melee range                                                                     |
| <a href="../weapons/Legendary%20Whip.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Whip</a>          | Presence  | Very Close | d6+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Startling:</strong></em> Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.                          |
| <a href="../weapons/Legendary%20Grappler.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Grappler</a>      | Finesse   | Close      | d6+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Hooked:</strong></em> On a successful attack, you can pull the target into Melee range.                                                             |
| <a href="../weapons/Legendary%20Hand%20Crossbow.md" class="text-amber-400 hover:text-amber-300 underline">Legendary Hand Crossbow</a> | Finesse   | Far        | d6+7 phy   | One-Handed | —                                                                                                                                           |
| <a href="../weapons/Braveshield.md" class="text-amber-400 hover:text-amber-300 underline">Braveshield</a>             | Agility   | Melee      | d4+6 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Sheltering:</strong></em> When you mark an Armor Slot, it reduces damage for you and all allies within Melee range of you who took the same damage. |
| <a href="../weapons/Knuckle%20Claws.md" class="text-amber-400 hover:text-amber-300 underline">Knuckle Claws</a>           | Strength  | Melee      | d6+8 phy   | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Doubled Up:</strong></em> When you make an attack with your primary weapon, you can deal damage to another target within Melee range.               |
| <a href="../weapons/Primer%20Shard.md" class="text-amber-400 hover:text-amber-300 underline">Primer Shard</a>            | Instinct  | Very Close | d4 phy     | One-Handed | <em class="text-amber-300 not-italic"><strong class="text-white font-semibold">Locked On:</strong></em> On a successful attack, your next attack against the same target with your primary weapon automatically succeeds.          |</p>
